import { type PresetCastEntry } from "./types";

export const TANG_SONG_MING_PRESETS: PresetCastEntry[] = [
  // -------------------------------------------------------------
  // Preset 1: 崇祯南迁 · 大明续命
  // -------------------------------------------------------------
  {
    id: "tang-song-ming-chongzhen-south",
    themeId: "tang-song-ming",
    scenarioIds: [
      "1961827555637175065",
      "293462445",
      "52693428",
      "Article:-3055829324161962699",
      "13063006782",
      "654859961",
    ],
    title: "天子临江:崇祯南迁的半壁江山",
    summary:
      "崇祯帝力排众议迁都金陵,李自成入空城北京,满清铁骑进抵山海关。金陵残明廷议如何划江而治与北伐勤王。",
    cast: {
      setting: {
        time: "崇祯十七年夏五月",
        location: "留都南京武英殿",
        crisis:
          "崇祯帝带太子与内阁南迁南京,北京陷落李自成之手,吴三桂引清兵入关。江南东林党人、守备武臣与流民起义军代表齐聚金陵,是联合顺军抗清,还是联虏平寇?",
        opening:
          "秦淮河畔丝竹未歇,殿外已是关塞烽烟。天子南渡,虽免了煤山殉国之惨,然而江南财赋之地被加征练饷激出民变,弘光旧勋与江北四镇拥兵自重。御座上的崇祯手按天子剑,半壁江山谁主沉浮?",
        rules: [
          "江南虽富但卫所兵废弛,防务完全依赖江北黄得功、高杰四镇客军",
          "东林党与复社文人把持留都言路,极度排斥北方南渡逃官与锦衣卫巡查",
          "江淮漕运被战火截断,金陵府库虽有丝绢但极度缺少战马与精铁",
        ],
      },
      playerCharacters: [
        {
          id: "player_emperor_chongzhen",
          name: "朱由检",
          identity: "大明崇祯皇帝",
          faction: "皇权正统与帝党亲信",
          archetype: "official",
          personality: "急躁多疑,刚愎决绝,心怀雪耻中兴之志却常苛责群臣",
          publicGoal: "收拢江南税赋,整肃江北四镇兵马,筹划挥师北伐光复北京",
          privateGoal: "彻底清除东林党对朝政的垄断,重建依附天子的厂卫特务情报网",
          decisionPower: "大明皇帝玺印、直接调遣御前锦衣卫与内帑私银调拨权",
          secret: "南逃途中秘密与闯军降将罗汝才旧部达成秘密受封免死协议",
          relationship: "痛恨江南文官贪婪惜财,但眼下防务全赖史可法协调江淮群雄",
          voice: "声色俱厉,时常长吁短叹,每言必及祖宗基业与亡国之耻",
          redLine: "绝不承认李自成的大顺伪政权,绝不与满清议和称臣削去大明帝号",
        },
        {
          id: "player_shi_kefa",
          name: "史可法",
          identity: "兵部尚书兼东阁大学士",
          faction: "东林清流与督师江北将士派",
          archetype: "general",
          personality: "清廉刚正,忠肝义胆,在复杂乱局中甘为社稷捐躯的正人君子",
          publicGoal: "督师江北,调和江北四镇骄兵悍将,筑牢淮河长江第一道防线",
          privateGoal: "避免南明陷入弘光潞王党争内讧,保全金陵朝廷政令通达",
          decisionPower: "江北督师帅印、调动淮安扬州粮秣大仓与签发武官升迁敕书",
          secret: "深知江北四镇总兵形同军阀各怀鬼胎,自己根本无法真正调动高杰与刘泽清部",
          relationship: "受天子倚重为柱石,但常被南京守备勋贵讥为不知兵的酸儒",
          voice: "慷慨悲壮,辞意恳切,引春秋大义与文天祥正气直抒胸臆",
          redLine: "绝不放弃扬州与淮北防线退缩至长江以南苟安",
        },
        {
          id: "player_zheng_chenggong",
          name: "郑森(郑成功)",
          identity: "国子监太学生 · 福建水师少将领",
          faction: "东南海商财阀与郑氏海上武装",
          archetype: "envoy",
          personality: "雄姿英发,兼具儒士气节与海上霸主野性,精通近代火炮与海运",
          publicGoal: "引福建郑家数万水师战船入长江,掌控金陵制水权,防备清军浮桥",
          privateGoal: "为郑氏集团谋得两广与福建海关关税全额截留权,建立海上独立王国",
          decisionPower: "指挥五百艘巨型福船铁甲战舰、调用西洋红夷大炮与海商军资",
          secret: "其父郑芝龙已私下派出密使携带生丝重礼北上接洽满清摄政王多尔衮",
          relationship: "深受崇祯皇帝青睐赐名'成功',与东林名士钱谦益有师生之谊",
          voice: "朗声英迈,兼具闽越海风与中原官话,极擅论述制海权与火器之利",
          redLine: "内阁若敢强令郑氏交出海师兵权给留都勋贵,立率水师返航厦门",
        },
      ],
      agentCharacters: [
        {
          id: "agent_qian_qianyi",
          name: "钱谦益",
          identity: "礼部尚书 · 江南士绅宗师",
          faction: "东林党领袖与江南豪绅庄园主",
          archetype: "official",
          personality: "文采冠绝一时,世故圆滑,私心极重,爱惜身名却又贪恋权位富贵",
          publicGoal: "反对加征江南田赋,力主划江偏安,休养江南士族生机",
          secret: "家中地窖藏有千万两白银,却在朝廷哭穷称江南已无余财可征",
          relationship: "桃李满天下,掌握南闱科举大权,对崇祯的急切催税极为阳奉阴违",
          voice: "辞藻华瞻典雅,微言大义,擅长用道德文章掩盖派系利益争夺",
          redLine: "绝不允许朝廷向苏州杭州松江等士绅田庄清查免税隐田",
          pressureMethod: "策动百名国子监生聚众伏阙上书,以士大夫清议迫使内阁搁置加税",
          openingLine: "陛下息怒!江南乃朝廷根本,若再横征暴敛,恐东南士民亦成李自成矣!",
        },
        {
          id: "agent_warlord_gaojie",
          name: "高杰",
          identity: "兴平伯 · 江北四镇总兵之一",
          faction: "流寇降军与跋扈军阀集团",
          archetype: "general",
          personality: "强悍凶残,骄横跋扈,从李自成阵营叛投而来的悍将,视兵马为命根",
          publicGoal: "朝廷必须全额发放百万两开拔犒军银,否则放任部属就地劫掠扬州",
          secret: "当年拐带李自成妻子邢氏叛逃,最惧李自成大军南下复仇,急需金银充实私囊",
          relationship: "表面接受史可法节制,私下蔑视南京朝廷,常持兵刃与文官咆哮",
          voice: "陕北粗嗓,满口污言秽语,杀气腾腾,视人命如草芥",
          redLine: "南京文官敢动江北兵额一兵一卒,立刻挥师渡江'清君侧'",
          pressureMethod: "手按腰间雁翎刀,数十名亲兵在殿外纵马狂奔咆哮示威",
          openingLine: "老子提着脑袋替你们守淮河!饷银拖欠了三个月,文官倒天天分润关税?拿银子来!",
        },
        {
          id: "agent_manchu_envoy",
          name: "范文程密使",
          identity: "多尔衮特使 · 潜伏说客",
          faction: "大清摄政王入关南下前哨",
          archetype: "envoy",
          personality: "阴鸷老练,洞悉明廷君臣弱点,擅长以'替君父报仇'为名行吞并之实",
          publicGoal: "劝诱南明朝廷承认满清接管黄河以北,诱使崇祯联清剿灭大顺李自成",
          secret: "怀揣多尔衮给南明勋贵的亲笔密札,许诺降清者世袭王侯高官厚禄",
          relationship: "通过南京降清富商建立地下联络站,悄然渗透金陵高层",
          voice: "阴沉冷静,剖析天下大势字字诛心,直击南明君臣的侥幸偏安心理",
          redLine: "南明若敢联合顺军合兵抗清,满清八旗铁骑便即刻渡淮屠城",
          pressureMethod: "当面出示吴三桂剃发降清的亲笔血书与山海关败绩战报,威慑全廷",
          openingLine: "崇祯爷,流贼弑君杀父夺你京陵,我大清替天讨贼!今日若拒联手,大兵过江片瓦不留!",
        },
        {
          id: "agent_nanjing_eunuch",
          name: "韩赞周",
          identity: "南京守备太监兼提督内桥",
          faction: "留都宦官势力与内桥库帑管领",
          archetype: "official",
          personality: "精明谨慎,世事练达,在留都经营数十年,掌握南京城防暗门与内帑钥匙",
          publicGoal: "维护留都禁卫戒严秩序,确保崇祯天子日常寝宫护卫万无一失",
          secret: "暗中扣留了北京城破前司礼监太监王承恩托人密运南下的最后一笔皇家内库金砖",
          relationship: "与崇祯既有主奴旧情,又暗中防备崇祯再次宠信北方南渡的魏忠贤余孽",
          voice: "尖细中透着南音的温软,处事圆滑周全,喜怒不形于色",
          redLine: "外省军将与东林文臣绝不能染指南京城门十三坊守御锁匙",
          pressureMethod: "轻摇宫中符节,城头红衣大炮与内桥羽林火铳手立即全员戒备",
          openingLine: "万岁爷,留都虽好,可兵马杂乱人心思动,老奴以为,城防兵权断不可假于外臣!",
        },
      ],
    },
    initialOptions: {
      player_emperor_chongzhen: {
        situation:
          "南京武英殿内,殿外高杰亲兵纵马咆哮逼饷,殿内钱谦益等东林诸臣叩首力阻加征江南赋税,更有多尔衮密使奉血书诱降。你携太子南渡金陵,龙袍带血,国仇家恨如万蚁噬心。留都百官都在盯着你,看你这位刚烈天子第一道圣旨要下给谁。",
        options: [
          {
            id: "A",
            title: "降旨《罪己责臣诏》,开内帑私银百万犒赏江北四镇",
            desc: "暂时吞下帝王骄傲,痛责自己识人不明,将南渡携带的私银尽数解往淮安、扬州,稳住高杰、黄得功等跋扈军阀,巩固江淮防线。",
            risk: "稳",
            crisisAction: true,
            impact: { stability: "↑", morale: "↑", support: "↓", resources: "↓↓" },
            forecast: [
              { agentId: "agent_qian_qianyi", lean: "back" },
              { agentId: "agent_warlord_gaojie", lean: "back" },
              { agentId: "agent_manchu_envoy", lean: "oppose" },
              { agentId: "agent_nanjing_eunuch", lean: "doubt" },
            ],
          },
          {
            id: "B",
            title: "联顺抗清:下密诏赦免李自成,封其为'秦王'合击八旗",
            desc: "以国仇重于私恨之大义,秘密遣使北上关中,承认李自成事实割据并授以封王帅印,约定南北夹攻山海关清军。",
            risk: "险",
            crisisAction: true,
            impact: { stability: "↓", morale: "↑", support: "↓↓", resources: "↑" },
            forecast: [
              { agentId: "agent_qian_qianyi", lean: "oppose" },
              { agentId: "agent_warlord_gaojie", lean: "oppose" },
              { agentId: "agent_manchu_envoy", lean: "oppose" },
              { agentId: "agent_nanjing_eunuch", lean: "doubt" },
            ],
          },
          {
            id: "C",
            title: "雷霆清洗:命锦衣卫当庭诛杀高杰,血洗留都抗税豪门",
            desc: "诱高杰入殿谢恩伏甲兵斩之,同时下令锦衣卫缇骑四出查封钱谦益等江南巨室金库,抄家充饷以充禁军。",
            risk: "赌",
            crisisAction: true,
            impact: { stability: "↓↓", morale: "↑↑", support: "↓↓", resources: "↑↑" },
            forecast: [
              { agentId: "agent_qian_qianyi", lean: "oppose" },
              { agentId: "agent_warlord_gaojie", lean: "oppose" },
              { agentId: "agent_manchu_envoy", lean: "doubt" },
              { agentId: "agent_nanjing_eunuch", lean: "back" },
            ],
          },
          {
            id: "D",
            title: "【天命破壁】焚毁宗藩俸禄册,诏令'天下田契重归流民战卒'",
            desc: "扯碎《大明祖训》宗藩例俸,颁发《中兴均田拓土令》:尽废天下宗室特权,江南私田悉数分与随军杀敌之将士与北方流民!以天子之身与三千万寒士立契!",
            risk: "狂",
            crisisAction: true,
            epigraph: "“天下非朱家一人之天下,若不能救万民于水火,这朱姓江山烧了又何妨?!”",
            impact: { stability: "↓↓", morale: "↑↑", support: "↑↑", resources: "↑↑" },
            forecast: [
              { agentId: "agent_qian_qianyi", lean: "oppose" },
              { agentId: "agent_warlord_gaojie", lean: "doubt" },
              { agentId: "agent_manchu_envoy", lean: "oppose" },
              { agentId: "agent_nanjing_eunuch", lean: "oppose" },
            ],
          },
        ],
      },
      player_shi_kefa: {
        situation:
          "你手握江北督师帅印,立于扬州大营与南京紫宸殿之间。黄得功与高杰为争夺防区拔刀相向,满清多尔衮的劝降信与吴三桂的飞檄已至案头。朝廷文武扯皮推诿,淮河防线千疮百孔,大溃败只在顷刻。",
        options: [
          {
            id: "A",
            title: "移师扬州筑'淮扬坚壁',以文臣之躯立誓死守江淮",
            desc: "不恋金陵权位,亲赴扬州督建壕沟城垒,节制四镇钱粮,以儒家忠义严明军纪,构筑寸土不让的坚固防线。",
            risk: "稳",
            crisisAction: true,
            impact: { stability: "↑", morale: "↑", support: "↑", resources: "↓" },
            forecast: [
              { agentId: "agent_qian_qianyi", lean: "back" },
              { agentId: "agent_warlord_gaojie", lean: "doubt" },
              { agentId: "agent_manchu_envoy", lean: "oppose" },
              { agentId: "agent_nanjing_eunuch", lean: "back" },
            ],
          },
          {
            id: "B",
            title: "施行'以虏制虏',以重金爵位结交左良玉八十万荆襄之众",
            desc: "调和江北四镇与武昌左良玉势力的宿怨,奏请朝廷破格封授左良玉为宁南王,引西军顺江东下合围徐淮。",
            risk: "险",
            crisisAction: true,
            impact: { stability: "↓", morale: "↑", support: "-", resources: "↓↓" },
            forecast: [
              { agentId: "agent_qian_qianyi", lean: "doubt" },
              { agentId: "agent_warlord_gaojie", lean: "oppose" },
              { agentId: "agent_manchu_envoy", lean: "oppose" },
              { agentId: "agent_nanjing_eunuch", lean: "back" },
            ],
          },
          {
            id: "C",
            title: "孤军突袭中原:亲率江淮锐士渡淮北伐,奔袭归德断敌粮道",
            desc: "趁清军入关立足未稳、八旗主力南下淮河前夕,亲提精骑兼程出击中原要冲,切断敌军粮道以乱其阵脚。",
            risk: "赌",
            crisisAction: true,
            impact: { stability: "↓", morale: "↑↑", support: "↑", resources: "↓↓" },
            forecast: [
              { agentId: "agent_qian_qianyi", lean: "oppose" },
              { agentId: "agent_warlord_gaojie", lean: "oppose" },
              { agentId: "agent_manchu_envoy", lean: "oppose" },
              { agentId: "agent_nanjing_eunuch", lean: "doubt" },
            ],
          },
          {
            id: "D",
            title: "【天命破壁】血祭梅花岭,立《浩气忠烈军宪》铸不灭精神图腾",
            desc: "在梅花岭前斩断退路,以督师血书传檄天下:'凡华夏男儿,头可断,发不可剃,身可死,志不可灭!'全军将士自戴孝布、自备棺木,将江淮化为埋葬侵略者的无底血肉磨盘!",
            risk: "狂",
            crisisAction: true,
            epigraph: "“我城在人存,城亡人亡!生做大明之鬼,死作击碎胡尘的九天雷霆!”",
            impact: { stability: "-", morale: "↑↑", support: "↑↑", resources: "↓↓" },
            forecast: [
              { agentId: "agent_qian_qianyi", lean: "doubt" },
              { agentId: "agent_warlord_gaojie", lean: "back" },
              { agentId: "agent_manchu_envoy", lean: "oppose" },
              { agentId: "agent_nanjing_eunuch", lean: "back" },
            ],
          },
        ],
      },
      player_zheng_chenggong: {
        situation:
          "你虽身着国子监襕衫,身后却有纵横闽粤的大明水师舰队与西方盖伦战船。郑芝龙来信催促保船自重、暗通清室;东林钱谦益等视你为武夫海盗,而崇祯帝却深情握住你的手叹道'惜乎卿非男儿,若为寡人重臣何愁社稷'。你的舰队就停靠在燕子矶江面。",
        options: [
          {
            id: "A",
            title: "锁江布防:引三百艘铁甲福船横江截流,断绝清军渡江企图",
            desc: "将郑氏水师精锐全部布设于瓜洲、焦山与长江要冲,凭借水师巨炮彻底切断南北航道,使清军铁骑望江兴叹。",
            risk: "稳",
            crisisAction: true,
            impact: { stability: "↑↑", morale: "↑", support: "↑", resources: "↓" },
            forecast: [
              { agentId: "agent_qian_qianyi", lean: "back" },
              { agentId: "agent_warlord_gaojie", lean: "back" },
              { agentId: "agent_manchu_envoy", lean: "oppose" },
              { agentId: "agent_nanjing_eunuch", lean: "back" },
            ],
          },
          {
            id: "B",
            title: "上奏《通海开埠疏》,以西洋重炮与南洋香料垄断留都财政",
            desc: "向崇祯帝提出特许郑氏全权开辟广州、泉州海外通商口岸,以海贸关税源源不断换取荷兰红夷大炮武装新军。",
            risk: "险",
            crisisAction: true,
            impact: { stability: "↓", morale: "↑", support: "↑", resources: "↑↑" },
            forecast: [
              { agentId: "agent_qian_qianyi", lean: "oppose" },
              { agentId: "agent_warlord_gaojie", lean: "doubt" },
              { agentId: "agent_manchu_envoy", lean: "oppose" },
              { agentId: "agent_nanjing_eunuch", lean: "doubt" },
            ],
          },
          {
            id: "C",
            title: "拘押亲父密使,断绝郑芝龙降清退路,逼全族向天子效死",
            desc: "当堂斩杀多尔衮派往郑府的满清说客,扣押父亲郑芝龙的私印,强行接管郑家七十二岛武装力量北上勤王。",
            risk: "赌",
            crisisAction: true,
            impact: { stability: "↓", morale: "↑↑", support: "↑", resources: "↑" },
            forecast: [
              { agentId: "agent_qian_qianyi", lean: "doubt" },
              { agentId: "agent_warlord_gaojie", lean: "back" },
              { agentId: "agent_manchu_envoy", lean: "oppose" },
              { agentId: "agent_nanjing_eunuch", lean: "back" },
            ],
          },
          {
            id: "D",
            title: "【天命破壁】扬帆全球大航海:以万艘战舰建'海上日不落'",
            desc: "不再困守大陆泥潭,向崇祯献上《坤舆万国全图》:以南明水师碾碎西方红毛番舰队,占领南洋与远东所有海峡!以倾国之力造万艘巨舰包抄辽东与天津卫,将大明蜕变为全球海洋帝国!",
            risk: "狂",
            crisisAction: true,
            epigraph: "“陆地有边界,而怒海没有尽头!凡战舰所至之重洋,皆是我大明之疆土!”",
            impact: { stability: "↓↓", morale: "↑↑", support: "↑↑", resources: "↑↑" },
            forecast: [
              { agentId: "agent_qian_qianyi", lean: "oppose" },
              { agentId: "agent_warlord_gaojie", lean: "doubt" },
              { agentId: "agent_manchu_envoy", lean: "oppose" },
              { agentId: "agent_nanjing_eunuch", lean: "oppose" },
            ],
          },
        ],
      },
    },
  },

  // -------------------------------------------------------------
  // Preset 2: 无安史之乱 · 大唐西征吐蕃
  // -------------------------------------------------------------
  {
    id: "tang-song-ming-anshi-no-rebellion",
    themeId: "tang-song-ming",
    scenarioIds: ["293462445"],
    title: "河陇定鼎:天宝年间的西征大议",
    summary:
      "安禄山在征召赴京途中被密诏处决,河北兵戈未起。玄宗朝廷将全部余力压向河西陇右,誓要踏平逻些,吐蕃密使却在朝堂上抛出南诏与大食的联兵警告。",
    cast: {
      setting: {
        time: "天宝十四载夏五月",
        location: "长安大明宫紫宸殿与三卫点校场",
        crisis:
          "安禄山奉诏入京被赐死于途,范阳精兵群龙无首,河北之乱未起。玄宗志骄,欲倾九节度之兵西讨吐蕃、克复河陇。然吐蕃大论密使携南诏与黑衣大食的联兵密约来朝,太子监国亦在暗中收拢兵权,朝堂对主战主和撕成两半。",
        opening:
          "范阳的狼烟终未烧起来,安禄山的首级悬在了潼关城头。长安久悬的心落了地,玄宗的雄心又涨了起来——他不许祖宗的河陇丢在吐蕃手里。可紫宸殿上,朔方军老将笃定能胜,吐蕃使节却笑称开元铁骑早已锈钝。太子在帘后听着,眼神比殿外的灯火更深。",
        rules: [
          "天宝府兵制已坏,精锐尽在九节度使边军之手,京师禁军久疏战阵",
          "唐蕃以赤岭为界屡经盟誓,吐蕃若知唐军主力西进,可联合南诏与黑衣大食夹击",
          "陇右河西运粮道单薄,军粮陆运每石成本高达六十贯,大军出塞日费斗金",
        ],
      },
      playerCharacters: [
        {
          id: "player_crown_prince",
          name: "李亨",
          identity: "皇太子 · 监国",
          faction: "东宫储贰与中央集权派",
          archetype: "official",
          personality: "隐忍持重,城府极深,在父皇翼下潜伏数十年,专等兵权交接的一日",
          publicGoal: "辅弼圣躬主持西征大计,以战功与内政威权逐步收回边镇节度之兵",
          privateGoal: "借帅印更迭之机,用亲信文臣替换安禄山系河北诸镇统兵,根除尾大不掉",
          decisionPower: "监国印绶、东宫六率卫队、数百道发往各镇的中书门下制敕用印权",
          secret: "已在安禄山旧部中安插了三名在东宫留质的降将,只待时机接管范阳十万铁骑",
          relationship: "对父皇玄宗既尽孝道又满怀戒惧,与权相杨国忠二世恩怨纠缠",
          voice: "温言恭谨,语带三分示弱,却在每个关节上滴水不漏地让权臣让步",
          redLine: "绝不容许炉火纯青的边镇军权再一次集于手握重兵且不可制的外姓之手",
        },
        {
          id: "player_guoziyi",
          name: "郭子仪",
          identity: "朔方节度副使 · 天德军使",
          faction: "朔方军班底与西北防务将领",
          archetype: "general",
          personality: "沉毅儒雅,老成持重,胸藏甲兵却谦和如布衣,素服人望",
          publicGoal: "统合朔方、河西、陇右三镇之兵,分进合击克复河湟,直捣逻些",
          privateGoal: "借西征整编之机把朔方军练成朝廷真正节制的中枢劲旅,不留私兵之讥",
          decisionPower: "朔方军行军大总管印、节制河西陇右诸道粮料转运与边防烽燧",
          secret: "早知吐蕃高原病对我军是灭顶之灾,私下已在陇西囤积五百车高原药材与驮畜",
          relationship: "与太子李亨在灵武结下知遇之情,却也要防京中权宦批战掣肘",
          voice: "沉稳如山,议论军政条理分明,从来不夸口,每言必称兵势地形",
          redLine: "绝不容许朝廷在军粮未备之时以一纸诏书催逼大军越陇山冒进",
        },
        {
          id: "player_wangwei",
          name: "王维",
          identity: "尚书右丞 · 唐蕃和亲副使",
          faction: "文馆清流与主和息兵派",
          archetype: "envoy",
          personality: "淡泊超然,诗禅双绝,骨子里深畏兵戈,认为国运应以文德怀柔四夷",
          publicGoal: "携和亲与市马之盟亲赴逻些,重订赤岭界碑,息兵保民",
          privateGoal: "借出使之便暗中探查吐蕃与南诏大食的联兵实情,为朝廷换一条退路",
          decisionPower: "持节使臣之印、鸿胪寺番使往来簿与河西商队秘密驿站通道",
          secret: "驼队中藏有一箱私铸的吐蕃文牒与舆图,若和议破裂便当场焚毁脱身",
          relationship: '与郭子仪交好但政见相左,被杨国忠讥为"只会吟山水诗的书生"',
          voice: "清雅蕴藉,出口即是诗眼,话锋软糯却绵里藏针",
          redLine: "绝不愿做拱手让出河西十州的'割地使',宁可死在路上也不签丧权之约",
        },
      ],
      agentCharacters: [
        {
          id: "agent_yangguozhong",
          name: "杨国忠",
          identity: "尚书右仆射 · 领剑南",
          faction: "外戚权相集团与京兆官僚",
          archetype: "official",
          personality: "狡黠贪婪,外历内荏,靠裙带上位,最怕太子与边将借战功架空自己",
          publicGoal: "促成玄宗御驾亲征或宰相监军,将西征军功与财赋都捏进自己手里",
          secret: "暗中扣留了郭子仪上报的粮道损耗奏章,欲在开战后以粮尽之罪治其死地",
          relationship: "视太子李亨为头号政敌,与吐蕃密使也在私下勾连了开市之利",
          voice: "嘴甜如蜜,见人说人话,见鬼说鬼话,惯以圣意为幌子行私利之实",
          redLine: "绝不容许太子一党借这次西征染指剑南与京兆的财赋大权",
          pressureMethod: "搬出玄宗'天可汗'遗威与万年历择吉,把主和派打成抗旨不前的嫌疑",
          openingLine:
            "陛下春秋鼎盛,胡儿之首唾手可得!此时不振军威,更待何时?谁主和,谁就是河西的罪人!",
        },
        {
          id: "agent_anshilushan",
          name: "安禄山(尸体犹存疑云)",
          identity: "范阳河东三镇节度使 · 已赐死",
          faction: "河北胡将集团与边镇契丹同罗思慕旧部",
          archetype: "general",
          personality: "壮硕狡黠,见貌作痴状,实则野心滔天,即便是死后余党仍不肯散",
          publicGoal: '由范阳三镇旧部欲为"冤死的节度使"讨一个说法与抚恤世袭',
          secret: "死前已密令心腹将数十万支军械藏匿于范阳、平卢民间地窖",
          relationship: "生前与杨国忠势如水火,死后其子安庆绪仍据范阳拥兵观望",
          voice: "京中由还记得他痴笑进谄的宦官代述,粗豪中透着森然寒意",
          redLine: "范阳兵权若被朝廷一分而空,旧部便以'守土'之名提兵抗拒制书",
          pressureMethod: "范阳监军急报称三镇士卒鼓噪,要求朝廷保留节度建制否则哗变",
          openingLine:
            "我安禄山侍奉陛下三十载,反贼二字竟比圣旨更快!(诸镇来使传其旧语)今日逼死臣者,明日谁守范阳?",
        },
        {
          id: "agent_tibet_envoy",
          name: "论·尚结赞",
          identity: "吐蕃大论密使 · 逻些王庭代言",
          faction: "吐蕃赞普朝廷与高原羌部联军",
          archetype: "envoy",
          personality: "倨傲善辩,通晓汉家典故,动辄以高原天险相胁,实则畏惧唐军合围",
          publicGoal: "以和盟为饵拖住唐军集结,暗促南诏大食援军抢在秋冬前就位",
          secret: "逻些王庭实已饥馑,若无大食援粮,高原过冬将溃,此来实为争取时间",
          relationship: "与已故的金城公主旧臣有旧,对长安的风土人物了若指掌",
          voice: "朗声如金石相击,引松赞干布旧盟与祖父辈和约压人,亦不忘以兵危恫吓",
          redLine: "绝不接受唐军以'巡边'名义越赤岭一步屯驻逻些左近",
          pressureMethod: "当殿出示南诏王与黑衣大食哈里发的联名金册,威胁三面合围",
          openingLine:
            "大唐的天可汗威震四海,可高原的雪不会说谎!唐军若入河湟一步,逻些的箭便射穿长安的梦!",
        },
        {
          id: "agent_goolishi",
          name: "高力士",
          identity: "内侍监 · 忠王旧伴",
          faction: "宦官内廷与皇帝私属亲卫",
          archetype: "official",
          personality: "机敏圆滑,历四朝不倒,深知皇帝心病的骨鲠老宦,极重听见真话后的分寸",
          publicGoal: "护持圣躬龙体,确保西征全程由天子亲制而不被边将窃取兵柄",
          secret: "私藏有江淮盐铁使的密折,言及国库实银仅够支应西征一半军需",
          relationship: "与杨国忠既合作又互相提防,对太子李亨恭敬中藏着多年的观察",
          voice: "嗓音温软,句句不离圣意,却总能不动声色地把皇宫里的刀光藏进帘幕",
          redLine: "禁中大内与皇城宿卫绝不能被外臣假借'监军'之名渗透",
          pressureMethod: "捧出玄宗腰牌,令殿前金吾卫听旨待命,示意御驾亲征并非说说而已",
          openingLine:
            "万岁爷龙马精神,老奴自当鞍前马后。可兵者凶器,诸位大人先想好胜了如何、败了如何,再议出兵不迟!",
        },
      ],
    },
  },

  // -------------------------------------------------------------
  // Preset 3: 万历苏州 · 工商集团与皇权缙绅三方博弈
  // -------------------------------------------------------------
  {
    id: "tang-song-ming-wanli-suzhou-uprising",
    themeId: "tang-song-ming",
    scenarioIds: ["52693428"],
    title: "机杼惊变:万历苏州的商税风暴",
    summary:
      "苏州织造局税监孙隆加征机户税银,织工罢织围署。江南工商集团欲借民变争商权,江南缙绅要守朝廷体统,皇权税使死守内库财源,三方在丝米之都反复博弈。",
    cast: {
      setting: {
        time: "万历三十年春四月",
        location: "苏州府阊门外织造局与税关",
        crisis:
          "织造局税监孙隆奉旨加派机户税银,苏州织工葛成率众罢织、围烧税署。工商集团要求废除苛税、开征商税自理;缙绅地主担忧民变动摇纲常;税监则必须如期解送内库银两。三方在苏州这座丝业都会激烈博弈,朝廷财源、民间生计与商人自治纠缠一处。",
        opening:
          "四月江南,本是蚕事正忙的光景。如今阊门内外机声俱歇,布商闭肆,织工千百人挤在税关前,葛成一纸揭帖贴上了照壁。织造局的孙太监攥着算盘不肯松手,退居林下的缙绅老爷们冷眼旁观。三拨人都盯着同一架织机,谁也不肯先收手。",
        rules: [
          "万历朝已开矿税之禁,税监四出,织造局所征机户税银直解内库,不经户部",
          "苏州机户逾万家、织工数十万,一旦罢织,商税、关税、田赋链路随之断裂",
          "江南缙绅以退居官员为核心,既怕朝廷苛政失民心,亦惧工商坐大动摇士绅本位",
          "朝廷除税额外,禁民间私铸钱、私开海禁,商税自理几无成例可循",
        ],
      },
      playerCharacters: [
        {
          id: "player_ge_cheng",
          name: "葛成",
          identity: "苏州机匠行会首领·罢织起事倡首",
          faction: "苏州织工与市井匠民",
          archetype: "commoner",
          personality: "粗豪刚烈,任侠重诺,深孚匠众之望,却对官商两家的门道知之不深",
          publicGoal: "迫使朝廷撤销加派机户税银,为织工争得粥米与谋生之路",
          privateGoal: "趁势为机匠行会争得议定工钱与税额的永久话语权,不再任人宰割",
          decisionPower: "能号令苏州上万织工罢织,可封锁织造局与税关,也可召集街巷民壮",
          secret: "已暗中与徽商盐帮接洽,若事不成便欲挟货东遁,另谋生路",
          relationship: "视税监孙隆为血仇,对缙绅顾家旧日恩义念念不忘,与丝商行会半信半疑",
          voice: "吴侬软语却中气十足,开口便是铜钱与米价,怒时满脸涨红",
          redLine: "绝不肯签任何先复工后议税的文书,怕缴械之后被人算后账",
        },
        {
          id: "player_gu_xiancheng",
          name: "顾宪成",
          identity: "致仕吏部郎中·无锡东林书院山长",
          faction: "江南缙绅与东林士人",
          archetype: "official",
          personality: "清峻峭直,以天下自任,极重名节与乡评,视税监为乱政之败类",
          publicGoal: "废罢矿税、裁撤在苏税监,还江南以清净,又不使民变酿成大祸",
          privateGoal: "借整肃税弊整饬江南吏治,把苏州工商利源纳入士绅乡评的监督之下",
          decisionPower: "东林书院声望、南北言路之门生故旧、联络江南府县缙绅联名上奏之权",
          secret: "其弟经商、家中田产亦出租机户,私下对商税自理之议并非全无心动",
          relationship: "与葛成暗通声气又怕其势大不可制,与孙隆势同水火,视瞒田逃赋豪绅为内贼",
          voice: "引经据典,字句峭拔,言必称民为邦本,又常以祖制压人",
          redLine: "绝不允许商人直接与内廷谈税而越过州府,更不肯替民变谋反背书",
        },
        {
          id: "player_liu_changyuan",
          name: "柳长源",
          identity: "苏州绸缎行会行首·当代巨贾",
          faction: "江南丝商行会与商税自理派",
          archetype: "magnate",
          personality: "精明和顺,长袖善舞,最善在官府与匠民间周旋,但求财路通达",
          publicGoal: "由行会代征机户税银、包缴关税,免除税监衙门层层盘剥",
          privateGoal: "借包商之制把织造、染坊上下游利源尽数拢入绸缎号体系,取士绅而代之",
          decisionPower: "苏州绸缎号银钱周转、机户购销把持、与南北客商议价网络",
          secret: "名下暗藏海关账目,历年夹带生丝出洋,舶来银两为官府所不知",
          relationship: "与葛成同闹民变却又提防匠人坐大,视孙隆为可贿买之豺狼,与顾宪成相敬如宾",
          voice: "软语温言,句句不离本钱利息,谈崩了便咳嗽转圜,绝不把话说死",
          redLine: "绝不肯公开与内廷抗辩而祸及家眷,更不肯替税监背那笔无底亏空",
        },
      ],
      agentCharacters: [
        {
          id: "agent_sun_long",
          name: "孙隆",
          identity: "苏州织造局税监·司礼监档头",
          faction: "内廷税监与皇权财源",
          archetype: "official",
          personality: "贪刻凌厉,深知税银即权柄,对上谄媚对下敲骨,不达解额不敢回京",
          publicGoal: "按额解送机户税银入内库,压平民变,保住织造局常驻苏州的差事",
          secret: "已克扣机户免税诰券与历年缂丝贡品折银归己,账册落在心腹书办手中",
          relationship: "畏顾宪成清议如虎,惧葛成民变切齿,专欲在柳长源身上榨出银两",
          voice: "官腔尖细,动辄搬出圣旨与厂卫,笑里藏刃,句句不离解银限期",
          redLine: "绝不敢让织造局税则有一文缩水,那比掉脑袋还可怕",
          pressureMethod: "调集税关胥吏与坊里弓手围堵罢织诸坊,并以通倭名目锁拿涉事商号",
          openingLine:
            "咱家奉的是皇命,解的是内帑!你们罢织也好、上疏也罢,少我一文钱,我就教苏州满城机户去大牢里过端午!",
        },
        {
          id: "agent_xu_wenbi",
          name: "徐文弼",
          identity: "苏州卫指挥佥事·管操捕盗",
          faction: "江南卫所武官系统",
          archetype: "general",
          personality: "粗鄙油滑的中层弁将,兵丁缺额吃空饷,最怕事态闹大自己吃挂落",
          publicGoal: "平息民变、守住衙门与税关,既不添乱又不担责,等巡抚指令",
          secret: "被孙隆私底下塞过银子压阵,却也受过葛成的旧日人情,两头不下注",
          relationship: "对孙隆半听半防,与葛成有巡城旧交,视顾宪成惹不起须躲着",
          voice: "南京官话带兵痞腔,粗声大气,开口闭口弟兄们与巡城规矩",
          redLine: "绝不肯在没有巡抚明文的情况下屠戮罢织百姓,那会连累全家",
          pressureMethod: "虚张声势地三日三换城门盘查,把查验的矛头对向商户辎重",
          openingLine:
            "都给老子听好!城门上箭顶着呢,谁要敢再烧税关,咱这营兵第一个拿人!识相的,跟爷回营喝杯茶!",
        },
        {
          id: "agent_xiao_kewang",
          name: "萧可望",
          identity: "苏州府通判·抚台衙门差委调停官",
          faction: "江南地方官府与州府吏治",
          archetype: "envoy",
          personality: "八面玲珑的府级官员,善于在缙绅、商人、税监之间递话传信,绵里藏针",
          publicGoal: "促成各方各退一步的体面收场,保住苏州课税的盘子与自己的考成",
          secret: "家中亦有丝庄股份,两头吃利,最怕真闹到停工亏本",
          relationship: "是顾宪成同乡门生,又受孙隆委托斡旋,与柳长源结过账目",
          voice: "慢声细气,出口必称为大家好,惯以下官递个话开头",
          redLine: "绝不肯把巡抚推上为难境地,更不肯为任何一方立书面字据",
          pressureMethod: "往来穿梭传话,把一方的让步粉饰成另一方的台阶,逼各方尽快落子",
          openingLine:
            "各位消消气,都消消气!抚台的意思呢,税银不是不给,是日子可以商量。咱们关起门来谈,何必让满城机声停成棺材铺?",
        },
        {
          id: "agent_craftsman_shen",
          name: "沈巧手",
          identity: "苏州织造名匠·花楼机改良人",
          faction: "染织匠户与行会匠人",
          archetype: "technician",
          personality: "手巧话少,执拗较真,一门心思扑在织机与颜料上,对税收门道知之不深",
          publicGoal: "保住织机改良的报酬与匠户身分,让上好花楼绸继续出在苏州",
          secret: "手头有改良花楼机的全套梭板图样,可一人抵三人织,欲献给行会换银子",
          relationship: "受雇于柳长源,敬重葛成仗义,却畏惧税监按其匠籍追缴巨款",
          voice: "憨厚词拙,三句不离机杼梭子颜料,被逼急了也会搁下梭子立誓",
          redLine: "绝不肯把图样白送给税监衙门的官织局,那等于把手艺卖了身",
          pressureMethod: "宣布新法损耗大、工价翻番,借行会之口向各方要价",
          openingLine:
            "我老头子织了一辈子绸,分得清糟粕好坏!把我的花样拿去官织局充公,我就不给行会出一根纬线!",
        },
      ],
    },
  },

  // -------------------------------------------------------------
  // Preset 4: 甲午北洋大胜 · 李鸿章坐大
  // -------------------------------------------------------------
  {
    id: "tang-song-ming-jiawu-navy-win",
    themeId: "tang-song-ming",
    scenarioIds: ["293462445"],
    title: "跃浪津门:大胜之后的北洋坐大",
    summary:
      "黄海一场恶战,北洋水师击伤吉野、重创本队,日军由攻转守。李鸿章挟盖世战功与北洋海陆权柄已成尾大不掉之势,朝中清流、帝党与日本议和使团的核心暗流同时绞动。",
    cast: {
      setting: {
        time: "光绪二十年(甲午)九月·黄海大捷后",
        location: "北洋水师提督署·威海卫,及天津直隶总督行辕",
        crisis:
          "北洋水师黄海大胜,日舰败退,中日和战之局骤变。李鸿章因大胜威望空前,更借势扩军索饷、兵权难制,北洋几乎成其私属;翁同龢等主战清流欲收军权于朝廷;日本则一面求和一面紧筹再战。甲午大胜后的晚清,走进了新的漩涡。",
        opening:
          "捷报传进紫禁城,光绪爷先是一愣,继而抚掌;可北洋的炮声一停,朝堂上的算盘声反倒响了。李鸿章身着黄马褂立于天津,一封拜表把请饷、扩舰、议和的话说得分明。海上的胜仗打完了,岸上的仗才刚开始——这一回,对手是自己的朝廷。",
        rules: [
          "北洋水师以购自英德的铁甲舰为底,军费常年依赖关税与举借洋款,户部并无余力",
          "清流以翁同龢为宗,早已视李鸿章结党营私、坐拥强兵为大患",
          "日本虽新败,但举国维新、缄默练兵,求和不过是缓兵之计",
          "各国驻华使节乘胜谋取权益,俄法德英在朝鲜与辽东各有算盘",
        ],
      },
      playerCharacters: [
        {
          id: "player_li_hongzhang",
          name: "李鸿章",
          identity: "直隶总督·北洋大臣·文华殿大学士",
          faction: "北洋海陆集团与淮系军功",
          archetype: "official",
          personality: "老谋深算而极善机变,功高震主又恋栈权位,至死抱着自强二字不肯放手",
          publicGoal: "借大捷保北洋现状,为海防争取足额军费与议和余地,稳住半壁洋务",
          privateGoal: "趁胜势交出可裁剪的虚功、留下买不到船炮的军权,坐实北洋藩篱之实",
          decisionPower: "北洋水陆全军调遣、津海关税权、江南机器制造局与轮船招商局调度",
          secret: "早有密电与其子李经方商议,若朝局不利便欲以条陈兵备堵人口舌",
          relationship: "与翁同龢政见相反、仇隙日深,与光绪君臣相疑,生死系于淮系与洋人之间",
          voice: "笃定从容,语带乡音,轻描淡写间把千斤重担说成平常事",
          redLine: "绝不肯交出津海关与北洋兵权,那无异于自断根基",
        },
        {
          id: "player_captain_ding",
          name: "丁汝昌",
          identity: "北洋水师提督·定远舰指挥",
          faction: "北洋水师将领集团",
          archetype: "general",
          personality: "忠朴整肃的宿将,治军严而待人宽,深知舰炮一发所系万千身家",
          publicGoal: "整补各舰以戒备日军复仇,守住渤海门户,不使一朝功业毁于懈怠",
          privateGoal: "为北洋水师官兵争得足额饷银与抚恤,保举麾下洋员与将领渐次升迁",
          decisionPower: "北洋舰队各舰调度、威海卫营房炮台、水师学堂练员及将领任命建议权",
          secret: "黄海之战旗舰定远亦受重创,深恐朝廷只记胜绩不肯拨银修舰",
          relationship: "受李鸿章提擢之恩,与清流素无往来,视洋员琅威理为练兵挚友",
          voice: "话语不多而沉稳,开口皆是舰况饷银兵丁,忧色藏于眉宇",
          redLine: "绝不肯拿虚报战功敷衍朝廷,更不肯把修舰银两挪作他用",
        },
        {
          id: "player_weng_tonghe",
          name: "翁同龢",
          identity: "军机大臣·户部尚书·帝师",
          faction: "帝党清流与主战士大夫",
          archetype: "official",
          personality: "博雅强项,嗜争而视淮系为心腹之患,骨子里认定督抚坐大即是国敌",
          publicGoal: "借北洋大捷之名收兵权于朝廷,革除督抚坐大、洋务自肥的积弊",
          privateGoal: "借查军费与考成之机,剪掉李鸿章羽翼,为帝党争得户部与海军实权",
          decisionPower: "户部财政核销、军机处章奏票拟、荐举朝命与钦派查案专责",
          secret: "甲午前曾以户部拮据为由减拨海军经费,此番若深究军费亦有跌足处",
          relationship: "与李鸿章形同水火,对丁汝昌亦多狐疑,与光绪有师生之谊",
          voice: "辞气峻急,好引圣贤经义,动辄以祖宗社稷压人",
          redLine: "绝不肯让北洋军费绕过户部循例奏销,更不肯久留淮系把持的海防重差",
        },
      ],
      agentCharacters: [
        {
          id: "agent_ito_hirobumi",
          name: "伊藤博文",
          identity: "日本内阁总理大臣·赴清议和专使",
          faction: "日本明治政府与陆军省",
          archetype: "envoy",
          personality: "精明枭悍,深知和约实为下一次战事备粮草的缓兵之谋",
          publicGoal: "以隐忍条款换得停战,得时间重建舰队、再谋朝鲜与辽东",
          secret: "陆海军缺损已极,求和只为遮羞,正暗中向英德续购新舰新炮",
          relationship: "与李鸿章有旧交又互为敌手,深忌翁同龢的清议与帝党主战",
          voice: "汉语流利,谈吐温文,绵里藏针,句句在算十年的账",
          redLine: "绝不接受日本向大清纳贡之类有损国体的条款",
          pressureMethod: "佯装示弱允诺撤兵,实则向各国公使散布北京主战误国的风声",
          openingLine:
            "中堂大人,胜败乃兵家常事。今日两国的和,是明日两国的和;只是这纸和约若迟迟不签,贵国朝堂上的炮声,只怕比黄海更响。",
        },
        {
          id: "agent_lang_weili",
          name: "琅威理",
          identity: "原北洋水师总查·英籍海战术指导",
          faction: "北洋洋员与英国顾问",
          archetype: "technician",
          personality: "耿直洋派,不谙中国官场,一意以英式操典与炮术为圭臬",
          publicGoal: "力主按新式炮术整训各舰、加配快炮,摒弃旧式拖带战法",
          secret: "收阅英国海军部密函,知列强必再索利权,急于撺掇北洋扩充武备",
          relationship: "与丁汝昌知交,与清流武备议论格格不入,被李鸿章视为可用的洋牌",
          voice: "生硬汉话夹着术语,动辄说皇家海军就是如此",
          redLine: "绝不容忍兵丁喝兵血、克扣弹药的那一套混珠",
          pressureMethod: "呈上黄海战后各舰受损清单与炮位加装图纸,逼朝廷表态拨款",
          openingLine:
            "提督阁下,请恕我直言!你们的胜,是拿老炮挨着打换来的。再不装快炮,下一场仗就是我的旧部重逢之忌日!",
        },
        {
          id: "agent_wen_tingshi",
          name: "文廷式",
          identity: "翰林侍读学士·帝党台谏",
          faction: "帝党清流与言官台谏",
          archetype: "official",
          personality: "慷爽激越,以清流自许,好发诛心之论,认北洋坐大即是国之大患",
          publicGoal: "参劾李鸿章拥兵自重,请朝廷收回海军与地方厘金之权",
          secret: "与翁同龢有师生之谊,若查办北洋军费至深,恐牵连自身保举过的洋务官员",
          relationship: "是翁同龢门下干将,视李鸿章为当世曹操,对丁汝昌亦多微词",
          voice: "诘问峻厉,引经据典,句句要拿账来见",
          redLine: "绝不肯为北洋说话,凡涉淮系之利必引章条款例力驳",
          pressureMethod: "连夜草成参折,联络台谏同列联衔,相约在公开庭堂之际递上",
          openingLine:
            "李中堂的战功,臣不敢掩;可北洋之兵,到底是朝廷的兵,还是李家的兵?今日不制,他日吞饵就钩,悔之晚矣!",
        },
        {
          id: "agent_sheng_xuanhuai",
          name: "盛宣怀",
          identity: "轮船招商局督办·电报总局总办",
          faction: "洋务商办企业与南北买办",
          archetype: "magnate",
          personality: "精明稳健的官商两栖人物,善以利权换扶持,账目心思极深",
          publicGoal: "借海战大捷为招商局与电报局争得官督商办的政策与资金",
          secret: "历年以报效之名行分润之实,账面做得漂亮,实利大半归于亲党",
          relationship: "得李鸿章多年提携,与翁同龢折冲樽俎,牵线洋商亦为其奥援",
          voice: "温润圆滑,开口必称商战即兵战,善把银钱账说成报国篇",
          redLine: "绝不愿把招商局轮船与电报线网划归官营,那会毁了他半生经营",
          pressureMethod: "以商可养军两全之策游说朝野,一旦旁人松动便促成官商合办之议",
          openingLine:
            "中堂,洋人的银行门口排着队要借给咱们银子。北洋要扩舰,洋人要利权,咱们正好拿别人的钱,办自己的事——这个局,只消朝廷点头。",
        },
      ],
    },
  },

  // -------------------------------------------------------------
  // Preset 5: 郑和航海技术未断 · 大明南洋争霸
  // -------------------------------------------------------------
  {
    id: "tang-song-ming-zhenghe-continued",
    themeId: "tang-song-ming",
    scenarioIds: ["1961827555637175065", "13063006782"],
    title: "宝船不歇:大明的南洋争霸",
    summary:
      "郑和宝船图籍未毁、匠户代代相传,下西洋的国策延续百年不绝。成化年间朝廷再议远洋,南洋诸番已成朝贡与海商的角逐场,安南、满剌加与西洋番商各怀心思,大明水师再度扬帆争雄。",
    cast: {
      setting: {
        time: "成化十七年春·第七次下西洋前夕",
        location: "南京龙江宝船厂与满剌加外海水道",
        crisis:
          "自永乐以来宝船技术传承不辍,历代皇帝断续遣使,南洋诸番邦渐视大明为海上宗主。然安南后黎朝借朝贡之名扩张侵并邻邦,满剌加苏丹两头下注,西洋佛郎机船影已现于天竺洋面。大明重启下西洋国策,朝中迁都北方的官僚却以虚耗国库力阻。",
        opening:
          "龙江宝船厂的锤声敲了五十年,图籍房的宝船样图换了三任守吏也一张未毁。成化爷在金台召见司礼监,说的是永乐爷旧话:遣使西洋,扬威万邦。可满朝堂响起一片劝谏声:北虏要紧,还是南洋要紧?码头上,满载瓷器的商船等得焦躁。",
        rules: [
          "宝船图籍与匠户世代相袭,九桅宝船与罗盘针经俱全,然造一艘耗银巨万",
          "南洋朝贡体系为利之所在,番邦以贡换市,海商借贡夹带私货已成惯例",
          "安南后黎朝兵强马壮,正借朝贡之名蚕食占城与真腊,番邦纷纷观望风向",
          "满剌加扼东西水道咽喉,苏丹在明与西洋商船之间两头取利,心思难测",
          "朝中以北虏为急务,户部视下西洋为无底洞,言官历次以虚耗国库力谏停办",
        ],
      },
      playerCharacters: [
        {
          id: "player_bao_chuan_ti_du",
          name: "王景弘",
          identity: "钦差正使·宝船水师提督太监",
          faction: "司礼监内官与下西洋使团",
          archetype: "envoy",
          personality: "沉稳老练,历七次远洋而不惊,深知海图针经如掌中纹路,对番邦虚实了如指掌",
          publicGoal: "率宝船队再下西洋,宣示朝贡宗法,护南洋海路商道安宁",
          privateGoal: "借下西洋之机为内官监掌得市舶税利,使宝船事业不被户部裁撤",
          decisionPower: "宝船舰队调度、使团人事任命、与番王会盟的礼单与册封敕书",
          secret: "已与满剌加苏丹暗通书信,许以厚赏换得让明船优先过港,此事不敢上闻",
          relationship: "与郑和同袍多年情谊深厚,视兵部侍郎阻航之议为笑谈,与户部官员势同水火",
          voice: "声若洪钟,言语间满是海事阅历,谈风谈浪谈针路,处处透着掌舵人的笃定",
          redLine: "绝不容许他人以空言废弃宝船,更不肯让多年心血图籍付之一炬",
        },
        {
          id: "player_liu_da_xia",
          name: "刘大夏",
          identity: "兵部侍郎·力主罢航的清流重臣",
          faction: "朝廷文官与北防务实派",
          archetype: "official",
          personality: "刚直清廉,以天下粮帛为念,视远洋虚名为误国之举,然亦有书生之执",
          publicGoal: "力阻下西洋重演耗空国库,把军费移向九边与漕运",
          privateGoal: "借机裁汰内官监掌海事之权,遏制司礼监借远洋扩充势力",
          decisionPower: "兵部调兵勘合、漕运与海防军费核定、廷议奏对的话语权",
          secret: "家中藏有宝船海图副本,若朝廷执意出海便欲面呈皇太后阻挠",
          relationship: "与王景弘水火不容,与户部同僚同气连枝,视番邦朝贡为虚套",
          voice: "语重心长,引经据典,开口祖宗成宪,闭口百姓脂膏",
          redLine: "绝不肯以国库之财供远洋虚名,更不肯让内官再掌一方兵权",
        },
        {
          id: "player_zhang_tong_shi",
          name: "张通事",
          identity: "满剌加归附华商·市舶牙行通事",
          faction: "南洋华商与市舶牙行",
          archetype: "magnate",
          personality: "八面玲珑,通晓番汉文字,在满剌加城中经营数代,两头生意做得风生水起",
          publicGoal: "借大明宝船压番邦盘剥,为华商争得平等议价的市舶行情",
          privateGoal: "独占满剌加至天竺的胡椒转口利源,挤开同在此地分利的安南商帮",
          decisionPower: "满剌加华商行会号令、番货定价话语权、为宝船队补给引航的人脉",
          secret: "暗中亦替安南商帮走货,若大明与安南交恶,他的两条船路立时只剩一条",
          relationship: "视王景弘为海上靠山,与满剌加苏丹有姻亲往来,对刘大夏的罢航之议恨得牙痒",
          voice: "闽腔夹番话,句句不离行市行情,笑脸迎人,账算得比谁都精",
          redLine: "绝不肯在明与安南之间明着选边,那会让他在满剌加的根基一夜崩塌",
        },
      ],
      agentCharacters: [
        {
          id: "agent_annan_envoy",
          name: "阮叔度",
          identity: "安南后黎朝贡使·兼领象队押运",
          faction: "安南后黎朝与南海扩张势力",
          archetype: "envoy",
          personality: "骄矜善辩,身负黎圣宗开疆余威,对占城蚕食得手而志骄意满",
          publicGoal: "以朝贡为名刺探大明下西洋虚实,为安南独霸占城真腊铺路",
          secret: "黎朝已暗中收买占城边将,欲借大明水师未至之隙速战灭占",
          relationship: "对大明表面恭顺实则腹诽,视满剌加苏丹为可拉拢之盟友,与张通事暗中较劲",
          voice: "汉话流利却字字带刺,礼数周全之下满是试探与锋芒",
          redLine: "绝不容许大明水师干预安南对占城的用兵,那是黎朝的国运所在",
          pressureMethod: "当众呈上占城请降表,以此胁迫大明承认安南既占之地,令宝船队名实两难",
          openingLine:
            "天使远来辛苦,可占城之民早归我大越教化久矣!大明若为区区荒土兴师,岂不寒了藩属的心?",
        },
        {
          id: "agent_suzhou_weihui",
          name: "林四海",
          identity: "泉州海商船帮首领·官贡夹带老手",
          faction: "闽广海商与民间走私船帮",
          archetype: "commoner",
          personality: "敢闯敢赌,风浪里趟出来的豪客,最恨朝廷禁海,最盼官船开道",
          publicGoal: "借宝船队之威让走私货船转正,挣一笔官船护航下的平安利",
          secret: "船底暗舱藏有违禁军器与南洋火器样件,预备带回泉州仿制",
          relationship: "奉张通事号令行事,与阮叔度的商帮有旧怨,对刘大夏的禁海论嗤之以鼻",
          voice: "粗声大气,满口风浪与海图行话,骂起人来天不怕地不怕",
          redLine: "绝不肯在满剌加港外被安南船截查货物,那是砸他全帮的饭碗",
          pressureMethod: "集结数十艘商船在宝船队桅影下壮声势,扬言安南敢动一船便火并到底",
          openingLine:
            "提督大人!南洋的海是大家的,凭什么他安南船要查咱的货?您的宝船在前头,咱们的船就跟在后头,谁的手痒谁先挨打!",
        },
        {
          id: "agent_manlagia_sultan",
          name: "穆罕默德·沙",
          identity: "满剌加苏丹·南洋霸主候选",
          faction: "满剌加王室与本地回回商团",
          archetype: "official",
          personality: "圆滑务实,深谙弱国在两强之间求存之道,见人说人话见鬼说鬼话",
          publicGoal: "借大明宝船压安南气焰,同时抬价向西洋商船收税,稳坐满剌加转口之利",
          secret: "已私下许西洋佛郎机商船减税一半,换得其火器保护,此事瞒着大明",
          relationship: "对王景弘礼敬有加实则相互算计,视安南为心腹大患,倚重张通事居中斡旋",
          voice: "马来腔的汉话流利圆滑,开口朝贡闭口情谊,句句都在讨价还价",
          redLine: "绝不肯让任何一方在满剌加港驻兵,那会把他变成别人的傀儡",
          pressureMethod: "以安南军逼境为由,向大明索要驻军与炮械,不成则以断补给相胁",
          openingLine:
            "天使容禀:小国屏息待命,只求大明兵船镇住四方!若连一尊大炮都不肯赐,小国只好投靠西洋人了!",
        },
        {
          id: "agent_baochuan_jiang",
          name: "薛宝船",
          identity: "龙江宝船厂掌线大匠·宝船世匠",
          faction: "宝船厂匠户与技术传承",
          archetype: "technician",
          personality: "讷言敏行,守祖业如守命根,一手桅帆龙骨功夫天下无双,最重器物传承",
          publicGoal: "保住宝船图籍与匠籍不废,造出新式尖底海船,续写下西洋的辉煌",
          secret: "已将祖传宝船图籍偷偷另誊一份藏于乡里,以备朝局反复之灾",
          relationship: "视王景弘为知遇恩主,对刘大夏欲毁图籍之议恨之入骨,与薛家匠户一荣俱荣",
          voice: "话少而沉,开口必谈船料船型水密舱,激动时声若闷雷",
          redLine: "绝不容许任何人焚毁宝船图籍,那是他全家几代人的命",
          pressureMethod: "率宝船厂全体匠户停工罢造,若不得准造之令便誓不再出船,以此逼朝廷表态",
          openingLine:
            "提督老爷,图在人在,图毁人亡!我薛家守着这堆纸五十年,就等皇上再点头的那一天。今日若不准造,请先把咱们全厂匠户的脖子捆了!",
        },
      ],
    },
  },

  // -------------------------------------------------------------
  // Preset 6: 南宋未亡 · 临安朝廷的海洋殖民帝国
  // -------------------------------------------------------------
  {
    id: "tang-song-ming-nansong-sea-empire",
    themeId: "tang-song-ming",
    scenarioIds: ["654859961"],
    title: "临安不坠:大宋的南洋立足",
    summary:
      "襄樊未破、崖山未沉,蒙元铁骑止步于江淮水网。南宋朝廷抓住喘息之机厉行海贸,市舶司扩张为海上命脉,泉州、明州商船直航占城真腊,一套以商养军、以海立国的方略,正把临安推向南洋殖民帝国之路。",
    cast: {
      setting: {
        time: "咸淳八年秋·蒙元南征受挫之后",
        location: "临安行在崇政殿与泉州湾市舶司",
        crisis:
          "蒙元水师在汉水受挫、江淮霖雨阻兵,大汗撤围北返,南宋暂得喘息。朝廷以市舶之利为命脉,欲乘隙开洋拓殖、以海养军。然朝廷财赋尽输战备,泉州蒲氏等海商大族挟市舶以自重,而蒙元使臣又携和议与恫吓并至,临安君臣须在眼前安逸与南洋基业间作出抉择。",
        opening:
          "襄樊的围解了,元军的船退回了汉水上游,临安城头悬了三年的大石终于落地。可太傅府的灯彻夜亮着:不打仗的日子更烧钱,百万水陆大军的粮饷总不能从天上掉下来。有人把目光投向泉州港外——那一片无边无际的海,也许是比江南更大的天下。",
        rules: [
          "南宋岁入市舶之利占天下财赋大宗,泉州、明州、广州三司为海贸命脉",
          "朝廷以禁钱出界、番货抽解为定制,海商夹带铜钱私货者罪至流徙",
          "泉州蒲氏一族掌控南海商路大半,其势与官近乎平起平坐,朝廷倚重亦忌惮",
          "蒙元水师虽暂退,但大汗必卷土重来,和议不过是又一次缓兵之计",
          "占城、真腊、三佛齐皆可贸易立足,但各邦习俗迥异,海商立埠需朝廷册封护佑",
        ],
      },
      playerCharacters: [
        {
          id: "player_jia_sidao",
          name: "贾似道",
          identity: "太师·平章军国重事·临安执政",
          faction: "临安朝廷主政集团",
          archetype: "official",
          personality: "权术老辣,多谋善断,以军事虚张声势而闻名朝野,极重私人权位",
          publicGoal: "以市舶之利充实军备,稳住临安局面,与蒙元周旋争取时间",
          privateGoal: "借开洋立埠之机把海贸利源揽入亲信之手,巩固执政地位",
          decisionPower: "临安中枢政令、市舶抽解章程、泉州等三司提举的任免大权",
          secret: "历年督战以虚报大捷邀功,名下亲党已暗中插手市舶税课,若清查必露",
          relationship: "视蒲氏海商为可取之利又深忌其尾大,对主战武将若即若离,与蒙元使者虚与委蛇",
          voice: "谈笑间机锋尽出,动辄引典故折人,表面谦和实则句句是权谋",
          redLine: "绝不容许武将借开洋立埠之名自立门户,威胁朝廷对他的倚重",
        },
        {
          id: "player_pu_shougeng",
          name: "蒲寿庚",
          identity: "泉州提举市舶·蒲氏海商宗主",
          faction: "泉州蒲氏海商集团",
          archetype: "magnate",
          personality: "精明强干,看准风向便下重注,视海洋为自家田宅,手腕与财势并重",
          publicGoal: "借朝廷开洋之议扩充蒲氏船队,拿下占城真腊的独家贸易权",
          privateGoal: "借市舶提举之权垄断海路咽喉,使蒲氏成为南洋真正的主宰者",
          decisionPower: "泉州船队调度、番货抽解定价、对南洋各埠商栈的号令",
          secret: "早已暗结蒙元使臣,若临安不保便欲携船队投元自保,此为一鱼两吃之局",
          relationship: "对贾似道既奉承又提防,视朝廷开洋为天赐良机,与武将主战派貌合神离",
          voice: "闽腔笃定,句句不离船货行情,谈利则眼亮,谈战则皱眉",
          redLine: "绝不肯让朝廷派官军常驻泉州水寨,那会搅了他经营多年的商路",
        },
        {
          id: "player_zhang_shijie",
          name: "张世杰",
          identity: "殿前都指挥使·沿江水军统帅",
          faction: "南宋主战武将与水军集团",
          archetype: "general",
          personality: "忠勇刚烈,以恢复中原为志,战则身先士卒,视和议为奇耻大辱",
          publicGoal: "以市舶之利练成一支可战水军,守住长江防线,图谋北伐",
          privateGoal: "借开洋练兵之名组建听命于自己的水军班底,免为朝廷党争所制",
          decisionPower: "沿江水军调度、殿前司禁军统辖、战船修造与兵饷支配",
          secret: "已暗中联络沿江义士,若朝廷决意议和便欲拥驾南巡以抗其议",
          relationship: "与贾似道政见相左、势同水火,与蒲寿庚互相利用,视蒙元使臣为仇寇",
          voice: "慷慨激昂,声震屋瓦,开口光复山河,闭口将士用命",
          redLine: "绝不肯接受与蒙元划江而治或称臣纳币的和议,那是背弃祖宗基业",
        },
      ],
      agentCharacters: [
        {
          id: "agent_yuan_envoy",
          name: "刘好谦",
          identity: "蒙元使臣·忽必烈汗特遣",
          faction: "蒙元汗廷与南下阵营",
          archetype: "envoy",
          personality: "老练圆滑,通晓汉法,软硬兼施是其本色,深谙南朝君臣各怀鬼胎",
          publicGoal: "诱南宋称臣纳币,拆散其市舶养军之策,为元军再攻争取时间",
          secret: "大汗嘱他务必探明泉州船队虚实,以定日后水陆并进之策",
          relationship: "与贾似道虚与委蛇,与蒲寿庚已有密约往来,视张世杰主战为眼中钉",
          voice: "汉话地道,辞令温恭中带森然,句句点到钱粮兵势",
          redLine: "绝不容许南宋借开洋之机暗中练兵壮大,那会让大汗的图谋落空",
          pressureMethod: "携大汗诏书与沿江军报同至,一面许和一面示兵,逼朝廷速决",
          openingLine:
            "贾太师,大汗的诚意,比黄金还实;大汗的耐心,却比弓弦还紧。称臣纳币,临安便安;若痴心妄想开洋练兵,那泉州港外的水,可淹不了汗廷的帐!",
        },
        {
          id: "agent_pu_lao",
          name: "蒲老",
          identity: "泉州造船名匠·蒲氏船场掌线",
          faction: "泉州船场匠户与技术传承",
          archetype: "technician",
          personality: "技艺通神,守口如瓶,一代造船绝活尽在掌中,最重匠人之道与家门名望",
          publicGoal: "保住蒲家船场的九桅巨船手艺,让泉州造出能越重洋的巨舰",
          secret: "已偷偷仿制番船水密舱工艺,若蒲氏南迁便带此技另起炉灶",
          relationship: "受蒲寿庚重金供养,与临安官船场老匠有旧谊,不屑朝廷禁海旧制",
          voice: "少言寡语,开口必是船料船型桅帆,皱眉时比骂人更叫人发怵",
          redLine: "绝不肯把祖传船图献于朝廷官营船场,那会让匠籍世代沦落",
          pressureMethod: "以拒造官船相要挟,扬言蒲氏船场的龙骨只认蒲氏令旗",
          openingLine:
            "官家要船,蒲家给船;可船场的规矩,是几代人的命换来的。谁想动我图籍、改我匠籍,就先把我的手指头剁了去!",
        },
        {
          id: "agent_zhancheng_envoy",
          name: "因陀罗",
          identity: "占城国使臣·真腊盟邦代表",
          faction: "占城真腊与南洋诸邦",
          archetype: "envoy",
          personality: "机敏善变,久闻临安富庶,一心引宋船入其国境以壮声威、得其市利",
          publicGoal: "促成占城与南宋互市通商,引宋船与火器入境以抗真腊侵逼",
          secret: "真腊正大举西侵,占城已失数港,急需宋船声援以稳人心",
          relationship: "视蒲寿庚为财神,恳请朝廷册封以为靠山,对蒙元使者避而不见",
          voice: "番腔汉话生硬热切,谈市利则眉飞色舞,谈战事则愁眉锁额",
          redLine: "绝不肯引狼入室让真腊借宋船之名反客为主,占城王位是其一族根本",
          pressureMethod: "以占城港埠相许,当众开出永久免抽解的条件,诱朝廷抢先立埠",
          openingLine:
            "天使天使!占城金瓯之港,愿为大宋水师常驻之所,税赋分文不收!只求朝廷船帆一到,真腊的兵就不敢再犯!",
        },
        {
          id: "agent_haishang_lao",
          name: "沈海生",
          identity: "泉州番坊买办·远洋老船工",
          faction: "泉州番坊与外洋船员",
          archetype: "commoner",
          personality: "半生飘海,见惯番邦风浪与人间冷暖,口直心热,识路如识家常",
          publicGoal: "带新船队闯出南洋航线,挣够银子赎身安家,不再做寄人篱下的番客",
          secret: "曾在三佛齐遇过番盗截船,深知海路凶险,却以此图换了船老大青眼",
          relationship: "奉蒲寿庚号令领航,视张世杰为可为百姓做主的官,与占城因陀罗有旧谊",
          voice: "满口闽腔夹杂番语,谈风浪如谈家常,讲起航线来两眼放光",
          redLine: "绝不肯在风汛不明时带船冒进,那会害了一船人跟他送命",
          pressureMethod: "散布南洋航线凶险的流言,以此抬升领航工钱,顺势把航路议价权握在手心",
          openingLine:
            "东家,海里的路我熟,可海里的命我输不起!要闯南洋,先给弟兄们把安家银备足,风汛一到,我沈海生第一个上船掌舵!",
        },
      ],
    },
  },

  // -------------------------------------------------------------
  // Preset 7: 安史之乱速平 · 父子君臣的权力清算
  // -------------------------------------------------------------
  {
    id: "tang-song-ming-anshi-quick-suppress",
    themeId: "tang-song-ming",
    scenarioIds: ["293462445"],
    title: "兴庆宫灯:乱平之后的父子清算",
    summary:
      "安史之乱爆发后迅速平定,两京光复。肃宗自灵武入主紫宸殿,太上皇回銮兴庆宫,平定之功与即位之疑纠缠一处,一场不见血的权力清算在父子君臣间展开。",
    cast: {
      setting: {
        time: "至德二载冬·两京光复之后",
        location: "长安大明宫紫宸殿与兴庆宫",
        crisis:
          "安禄山、史思明授首,乱事迅速平定,两京光复。然肃宗于灵武未经册宝即位,法统屡遭朝野窃议;太上皇自蜀回銮,身边龙武军与旧臣依旧。灵武拥立功臣、玄宗旧党、新贵宦官三方角力,肃宗既要坐实正统,又要清算太上皇留下的旧班底。",
        opening:
          "至德二载,长安的残烟未散,安禄山、史思明的首级已传遍河北。太上皇自蜀中回銮,肃宗在灵武即位,两京收复之功成了满朝争抢的赏格。兴庆宫的旧灯,紫宸殿的新筹,父子君臣之间,一场不见血的清算正在展开。",
        rules: [
          "至德两载两京虽复,然中原州县残破、府库空虚,平叛所倚朔方军与回纥兵皆劲悍难制",
          "肃宗以灵武即位未经册宝之礼,群臣私议其法统有亏,尊号须仰太上皇诏令",
          "回纥助唐收复两京,约克城之日金帛子女归回纥,京畿已遭劫掠,民怨正盛",
          "太上皇仍掌兴庆宫禁卫与内侍之权,陈玄礼、高力士等旧臣犹存威望",
        ],
      },
      playerCharacters: [
        {
          id: "player_suzong_liheng",
          name: "李亨",
          identity: "大唐肃宗皇帝·自灵武即位",
          faction: "灵武拥立功臣与朔方军班底",
          archetype: "official",
          personality: "沉机善断而性多猜忌,乱世中夺位自立,既怀中兴之志又深忌父皇与旧臣",
          publicGoal: "平定残寇、回銮长安,以克复两京之功坐实正统皇位",
          privateGoal: "彻底清除太上皇在朝堂的旧党与话语权,使政令皆出紫宸殿",
          decisionPower: "天子诏敕、朔方及诸道勤王兵马调度、凤翔行在文武任免",
          secret: "马嵬坡之变背后实有其授意,至今秘而不宣的疑案压在他心头",
          relationship: "与太上皇表面孝悌实则提防,倚重李辅国制衡诸将,视李泌为腹心",
          voice: "语多含蓄,喜怒不形于色,偶露锋芒便令满殿噤声",
          redLine: "绝不容许太上皇在长安重新坐朝理事,更不肯让兵权落回玄宗旧部之手",
        },
        {
          id: "player_li_guangbi",
          name: "李光弼",
          identity: "天下兵马副元帅·朔方节度使",
          faction: "朔方河东平叛军功集团",
          archetype: "general",
          personality: "治军严整、号令如山,智勇兼备而性情沉郁,功高而不善自处",
          publicGoal: "追剿史思明余党,巩固河洛防线,使中原重获安宁",
          privateGoal: "使麾下将士的封赏抚恤足额兑现以全军心,免遭鸟尽弓藏之祸",
          decisionPower: "朔方河东两镇兵马、太原府军储、诸道勤王军节制符契",
          secret: "已察觉肃宗以监军宦官分其兵权,暗中留了一手制衡用的将士名册",
          relationship: "与郭子仪齐名而互相推重,对肃宗猜忌诸将之心了然于心,与李辅国势同水火",
          voice: "寡言少语,言出必断,遇军务则字字如铁",
          redLine: "绝不容许监军宦官在阵前乱传诏令贻误军机",
        },
        {
          id: "player_li_bi",
          name: "李泌",
          identity: "白衣山人·肃宗股肱谋主",
          faction: "皇帝私人心腹与无官位之谋臣",
          archetype: "official",
          personality: "旷达聪慧,好黄老之学,运筹帷幄而淡泊名利,屡辞官职甘居幕后",
          publicGoal: "助肃宗稳定中枢、收拢功臣,以最小代价完成政权过渡",
          privateGoal: "保全太上皇性命与体面,避免一场血流成河的父子相残",
          decisionPower: "出入禁中密参帷幄、代拟制敕、联络朔方河东诸将的密使通道",
          secret: "私心以为肃宗逼杀父皇必失天下人心,暗中已在太上皇身边安插眼线",
          relationship: "为肃宗倾心纳谏之人,与李光弼有旧交,对李辅国专权深以为忧",
          voice: "语带玄机,常以黄老寓言进谏,字句平和却句句切中要害",
          redLine: "绝不肯卷入诛杀太上皇的密谋,那会毁了他一生的道义与名节",
        },
      ],
      agentCharacters: [
        {
          id: "agent_li_fuguo",
          name: "李辅国",
          identity: "判元帅府行军司马·肃宗心腹宦官",
          faction: "肃宗内廷宦官与元帅府行营",
          archetype: "official",
          personality: "阴鸷果敢,借拥立之功揽权,最恨玄宗旧阉与武将掣肘",
          publicGoal: "借清算玄宗旧党之机,把禁中宿卫与奏章批红之权尽收己手",
          secret: "私刻玉印代行批答,专擅军政文书往来,诸司多不知晓",
          relationship: "为肃宗头号心腹,与陈玄礼、高力士不共戴天,与李光弼暗中争兵",
          voice: "尖利短促,动辄抬出圣意压人,句句都是刀",
          redLine: "绝不容许太上皇回京后重掌禁军与内侍省",
          pressureMethod: "指使禁军校尉罗织罪名,当廷构陷玄宗旧臣图谋不轨",
          openingLine:
            "太上皇身边那些人,还当是开元天子临朝的时候!万岁爷,让老奴替您扫干净兴庆宫的门,省得野草又长回紫宸殿来!",
        },
        {
          id: "agent_chen_xuanli",
          name: "陈玄礼",
          identity: "龙武大将军·太上皇扈从",
          faction: "禁军龙武军与太上皇旧臣",
          archetype: "general",
          personality: "忠厚耿介,马嵬坡上亲手送走杨国忠,对太上皇却始终心存愧怍",
          publicGoal: "保太上皇平安终老,守兴庆宫禁卫不失于人手",
          secret: "马嵬坡兵变的真正策动者讳莫如深,他自知曾受李亨密使示意",
          relationship: "随太上皇入蜀又回京,是玄宗身边最后的武力屏障,与李辅国不共戴天",
          voice: "沉痛寡言,常以旧臣自居,句句都是君臣名分",
          redLine: "绝不肯交出龙武军号令,那无异于把太上皇的命交给仇人",
          pressureMethod: "以护驾为名亲率龙武军于兴庆宫外列队戒严,示以武力自保",
          openingLine:
            "陛下与太上皇,都是臣的君父!谁要敢动兴庆宫的一草一木,先问问龙武军三千儿郎答应不答应!",
        },
        {
          id: "agent_gao_lishi",
          name: "高力士",
          identity: "内侍监·太上皇贴身老宦",
          faction: "内廷旧宦与太上皇私属",
          archetype: "official",
          personality: "历四朝不倒的老宦,最懂分寸,明知大势已去仍舍命护主",
          publicGoal: "守住太上皇的体面与性命,不使旧君晚景凄凉",
          secret: "藏有玄宗在蜀中拟就的手诏底稿,若肃宗逼迫太上皇太甚或可一用",
          relationship: "与李辅国同阉而势同水火,视陈玄礼为唯一可托之人,深悉肃宗心思",
          voice: "嗓音温软,句句不离老奴,绵里藏针,最能消解刀兵之气",
          redLine: "绝不肯坐视太上皇被人逼杀,那会让他一世忠名蒙尘",
          pressureMethod: "捧太上皇赐物当众示恩,又暗递玄宗手书,搅动肃宗心防",
          openingLine:
            "老奴伺候太上皇一辈子,只知道一件事:做儿子的,再大的怨气,也不能让外头的人,笑话他的父亲!",
        },
        {
          id: "agent_huigu_envoy",
          name: "毗伽特使",
          identity: "回纥可汗特使·助唐功臣",
          faction: "回纥汗廷与漠北骑兵集团",
          archetype: "envoy",
          personality: "骁勇豪迈,以助唐平乱自居,言语间满是恩人般的傲气",
          publicGoal: "催讨助战封赏与互市之利,趁唐廷内斗坐收更多马价",
          secret: "回纥大军久驻中原,粮秣消耗甚巨,急于得赏而返却不肯示弱",
          relationship: "以收复两京首功自居,对肃宗朝廷软硬兼施,视李辅国之流为可欺的阉人",
          voice: "汉话生硬,开口便是功劳与马价,动辄提可汗之名压人",
          redLine: "绝不肯在封赏未足时空手北返,那会令他在可汗面前失尽颜面",
          pressureMethod: "放出回纥大军逗留京畿不归的风声,迫使朝廷尽快兑现封赏",
          openingLine:
            "大唐的皇帝,回纥的刀子替你们砍了叛贼,帐下的儿郎还饿着肚子!赏赐不到,我们就在长安城外多住几冬!",
        },
      ],
    },
  },

  // -------------------------------------------------------------
  // Preset 8: 黄巢之乱未起 · 大唐藩镇自请赴阙
  // -------------------------------------------------------------
  {
    id: "tang-song-ming-huangchao-not-risen",
    themeId: "tang-song-ming",
    scenarioIds: ["1961827555637175065"],
    title: "恩诏如雨:无黄巢之乱的大中削藩",
    summary:
      "宣宗厘清盐政,私盐枭首受抚,黄巢之乱终未兴起。河北藩镇见朝廷宽猛相济,纷纷自请赴阙纳质,文景式的削藩夺权,正借一道道恩诏悄然推进。",
    cast: {
      setting: {
        time: "大中十三年春·两河无事",
        location: "长安大明宫延英殿与河北诸镇军府",
        crisis:
          "宣宗厘清盐政、蠲免积欠,私盐枭首王仙芝受抚入朝为盐铁巡官,黄巢之乱终未兴起。河北藩镇见朝廷宽猛相济,卢龙张允伸首倡自请赴阙,魏博诸镇却观望犹疑。朝廷欲行文景式削藩夺权,藩镇牙兵、回鹘边患与盐利之争纠缠一处。",
        opening:
          "大中十三年,宣宗爷的盐政像一场春雨,把山东的私盐枭首淋成了朝廷的盐铁巡官。黄巢的刀,终究没举起来。河北藩镇看在眼里,自请赴阙的奏章,一本接着一本送到大明宫。削藩的盛世,正借着一纸纸恩诏,悄悄走来。",
        rules: [
          "大中朝府库渐丰,盐利岁入为天下财赋之半,禁私盐之令极严而犯者不绝",
          "河北诸镇世袭相承数十年,军中牙兵骄横,视节帅为雇主,非朝廷诏令所能尽制",
          "宣宗以严驭臣著称,然畏宦官如虎,枢密使掌禁中机务,与宰相并驾",
          "沙陀、党项部落居代北边地,屡为边患,朝廷须留宿重兵防秋",
        ],
      },
      playerCharacters: [
        {
          id: "player_xuanzong_lichen",
          name: "李忱",
          identity: "大唐宣宗皇帝·人称小太宗",
          faction: "皇权与中书宰相集团",
          archetype: "official",
          personality: "明察严毅,心思深不可测,好微行察访,以肃清积弊自任",
          publicGoal: "以文景之术抚藩镇、削方镇之权,使朝廷威信重归河北",
          privateGoal: "收回河北诸镇自擅的财赋兵马,为后世子孙永绝藩镇之患",
          decisionPower: "天子诏敕、诸道节帅任免、盐铁户部财赋调度、禁中批红",
          secret: "身患隐疾自知年命不久,故削藩之术求稳求速,不愿多生枝节",
          relationship: "倚重令狐绹等文臣,对河北藩帅表面优渥内心刻刻提防,对枢密宦官深怀戒惧",
          voice: "辞气峻冷,好以细节问难群臣,一针见血不留情面",
          redLine: "绝不容许藩镇世袭之制延续到下一代,更不肯向宦官让步政事",
        },
        {
          id: "player_zhang_yunshen",
          name: "张允伸",
          identity: "幽州卢龙节度使·同中书门下平章事",
          faction: "卢龙镇与主动归朝派藩帅",
          archetype: "general",
          personality: "识时务而重身家,在骄兵环伺中左右逢源,是河北诸镇中最肯向朝廷输诚者",
          publicGoal: "率卢龙镇纳质入朝,为子孙谋一个体面的出路",
          privateGoal: "借归朝之机保全卢龙牙兵与军资,不使多年家业一朝倾覆",
          decisionPower: "卢龙镇兵马钱粮、幽州军府印信、入朝随行的牙兵卫队",
          secret: "卢龙牙兵凶悍难制,若朝廷强夺其兵权,恐军士鼓噪反噬其身",
          relationship: "得宣宗赐姓推恩而深感皇恩,与魏博韩允中暗中互通声气,视宰相令狐绹为朝廷对头",
          voice: "粗中有细,开口必称皇上恩德,却句句都要替手下弟兄讨赏钱",
          redLine: "绝不肯签下让卢龙牙兵就地遣散的条款,那会要他老命",
        },
        {
          id: "player_wang_xianzhi",
          name: "王仙芝",
          identity: "私盐枭首·新授盐铁巡官",
          faction: "淮南山东私盐贩与受抚降人集团",
          archetype: "magnate",
          personality: "狡黠豪爽,惯于刀口舔血,如今初沐皇恩,既想保富贵又想护旧部",
          publicGoal: "以盐铁巡官之身整顿私盐之患,借朝廷名分洗白身家",
          privateGoal: "保举昔日麾下盐枭旧部各得安身之职,不留后患",
          decisionPower: "盐铁巡务缉私权限、两淮盐场旧部人脉、对盐商盐价的议定话语权",
          secret: "早年私盐所得金银尚埋藏于乡里,以备朝廷反悔之日东山再起",
          relationship: "视黄巢为割头换命的旧识,对朝廷既感恩又疑虑,听命于令狐绹的招抚安排",
          voice: "市井粗嗓,混着江湖切口,谈到盐利便眉飞色舞,谈到官府便半信半疑",
          redLine: "绝不肯交出私盐网络与旧部名录,那是他保命的本钱",
        },
      ],
      agentCharacters: [
        {
          id: "agent_linghu_tao",
          name: "令狐绹",
          identity: "中书侍郎·同平章事",
          faction: "中书宰相与主抚朝臣",
          archetype: "official",
          personality: "谨厚老成,长于调和,视招抚与削藩为一场温水慢煮的棋局",
          publicGoal: "以恩信感化河北诸镇自请交权,不动刀兵完成削藩",
          secret: "其子令狐滈结党纳贿,若朝廷清丈盐政必被牵连",
          relationship: "为宣宗最信重的宰相,与枢密宦官暗中较劲,主持王仙芝招抚之局",
          voice: "温吞绵软,以退为进,句句都是给你留体面的官场话",
          redLine: "绝不肯让削藩演成武力讨伐,那会毁了他半世宰相的令名",
          pressureMethod: "以分封美官诱藩帅子弟入京为质,又暗示魏博若不动则朝廷另有安排",
          openingLine:
            "张公、韩公,圣上待河北诸镇,是拿儿子待老子啊!交出兵权,爵禄照旧;若不交,可就别怪朝中的刀剑,不认旧日的情分了!",
        },
        {
          id: "agent_han_yunzhong",
          name: "韩允中",
          identity: "魏博节度使·检校司空",
          faction: "魏博镇与观望自保派藩帅",
          archetype: "general",
          personality: "城府极深,视兵权如命,对朝廷的恩诏来者不拒、去者不留",
          publicGoal: "保住魏博三州兵权与世袭之利,又不得罪朝廷体面",
          secret: "暗中已联合河朔诸镇约定,若朝廷强取一镇之兵,则诸镇共守以静制动",
          relationship: "与张允伸表面上同进退、暗地里互不相让,视令狐绹为笑脸藏刀之人",
          voice: "声若洪钟,满口忠君,实则把每句圣恩都听成催命的令",
          redLine: "绝不肯让朝廷在魏博三州设一道监军刺史插手军府",
          pressureMethod: "以牙兵巡城、罢市示威,把魏博说得危机四伏,使朝廷不敢轻动",
          openingLine:
            "末将谢圣上隆恩!只是魏博牙兵素来只听军府号令,朝廷忽然要收印绶,怕是要激起兵变——这乱子,末将一人可担不起!",
        },
        {
          id: "agent_huigu_horse",
          name: "阿联隗罗",
          identity: "回鹘可汗使臣·入贡互市",
          faction: "回鹘汗廷与漠北诸部",
          archetype: "envoy",
          personality: "精明强悍,奉可汗之命观望唐廷削藩虚实,好乘隙索市马之利",
          publicGoal: "以朝贡互市为名,探明河北兵变虚实,乘势抬升马价",
          secret: "回鹘连年大雪,马匹牲畜折损甚多,急需与唐互市以渡难关",
          relationship: "与卢龙镇多有马市往来,视唐廷削藩后的边防空虚为可乘之机",
          voice: "汉话生硬,开口牛羊马价,闭口可汗陛下,句句都在讨便宜",
          redLine: "绝不肯接受唐廷压低马价或断绝互市的条款",
          pressureMethod: "抬出可汗厉兵秣马之事,暗示唐廷若削减边军,回鹘便不守约",
          openingLine:
            "大唐朝堂调兵遣将,可草原的箭已经搭上弦了!要么把互市的价钱谈妥,要么等可汗的骑兵,来给长安的旧街换一换土!",
        },
        {
          id: "agent_huangchao",
          name: "黄巢",
          identity: "曹州私盐商·未起事的枭雄",
          faction: "山东私盐集团与失地流民",
          archetype: "magnate",
          personality: "深沉有文采,性刚果而多疑,如今暂敛锋芒,冷眼看朝廷如何处置旧盐枭",
          publicGoal: "谋一个能保山东盐帮兄弟周全的出路,不愿轻身犯险",
          secret: "早已遍结山东豪强与饥民,一旦朝廷反悔仍可聚众而起",
          relationship: "与王仙芝并称盐帮双雄,看令狐绹的招抚虚情假意,对朝廷始终半信半疑",
          voice: "谈吐不俗,颇通诗书,常以一句闲话点破官场险恶",
          redLine: "绝不肯交出私盐分利与乡里人脉,那是他活命的根基",
          pressureMethod: "暗中串联流民散布朝廷苛盐之论,逼朝廷把招抚的价钱加足",
          openingLine:
            "王大哥得了官身,我黄巢先道一声喜!只是这官家给的官,向来是给得了也收得回——刀把子不攥在自己手里,梦里都睡得不安稳!",
        },
      ],
    },
  },

  // -------------------------------------------------------------
  // Preset 9: 澶渊之盟破裂 · 宋辽全面开战的天书变法
  // -------------------------------------------------------------
  {
    id: "tang-song-ming-chanyuan-war",
    themeId: "tang-song-ming",
    scenarioIds: ["52693428"],
    title: "天书战车:澶渊决裂之后的大宋变法",
    summary:
      "澶渊之盟墨迹未干,辽人背盟南犯。真宗借天书神瑞之名行变法理财、增赋扩军之实,寇准力主决战,王钦若力劝息兵,宋辽由盟转战,汴京与雄州同时开动。",
    cast: {
      setting: {
        time: "大中祥符元年春·天书降神之后",
        location: "汴京大内滋福殿与河北雄州前敌行营",
        crisis:
          "澶渊之盟甫定,辽人背盟南犯,真宗震怒决意倾国再战。朝中王钦若等主和派谋阻,寇准等主战派请缨。真宗借天书神瑞之兆行变法理财、增赋扩军,以天意压朝议,宋辽由盟转战,河北河东烽火重燃。",
        opening:
          "澶渊的墨迹还没干透,辽人的马蹄已踏过白沟河。真宗爷攥着天书封禅的敕书,眉眼里藏着雪耻的雷。王钦若劝他息兵,寇准求他亲征,雄州的烽燧一夜连点三起——大宋的变法与战车,在同一天发动。",
        rules: [
          "景德澶渊之盟岁币三十万,辽人背盟再犯,府库因封禅祀天益形支绌",
          "真宗崇道佞神,天书降于左承天门,朝野以祥瑞媚上者众,封禅之议已定",
          "宋军禁军厢军百万而冗员甚众,河北屯田久废,粮道依赖汴河漕运",
          "辽主以萧太后与诸宿将统骑兵,秋高马肥必举族南牧,边州须整备防秋",
        ],
      },
      playerCharacters: [
        {
          id: "player_zhenzong_zhaoheng",
          name: "赵恒",
          identity: "大宋真宗皇帝·受命天书",
          faction: "皇权与主战变法集团",
          archetype: "official",
          personality: "好名而怯战,深以澶渊城下之盟为耻,既欲雪耻又怕亲临锋镝,常以天命自壮",
          publicGoal: "借天书神瑞总摄人心,变法理财、整顿禁军,筹备与辽决战以雪前耻",
          privateGoal: "借天书封禅与对辽战功压服朝议,使主和派再无置喙余地",
          decisionPower: "天子诏敕、三司财赋调度、殿前侍卫亲军与亲征行营",
          secret: "澶渊议和时曾密使辽营许诺岁币,恐被史官书为城下之盟,此耻日夜焚心",
          relationship: "疑王钦若等主和之臣心怀贰意,倚寇准为胆,对辽使又和又战举棋不定",
          voice: "优柔中偶露刚愎,言必称天命祖宗,遇难处则沉吟半晌",
          redLine: "绝不肯再签一份岁币多于澶渊之盟的和约,那比亡国更让他无颜",
        },
        {
          id: "player_kou_zhun",
          name: "寇准",
          identity: "枢密使·同平章事",
          faction: "中书主战派与河北边防集团",
          archetype: "official",
          personality: "刚直峻烈,胆识过人,以社稷为任,敢犯颜直谏,是澶渊之盟的总导演",
          publicGoal: "趁辽背盟之机一战定河北,废岁币、收燕云,重振大宋军威",
          privateGoal: "借变法整顿三司财赋,裁汰冗官冗兵,把兵权财权收归中书",
          decisionPower: "枢密院调兵印信、三司财计审阅、河北河东诸路宣抚之权",
          secret: "暗中已联络河北义军与地方豪强,若战事不顺便欲虚张声势以震辽军",
          relationship: "为真宗所倚为社稷臣,与王钦若势同水火,视辽使为不共戴天之敌",
          voice: "声若金石,直言不讳,常以臣请陛下亲征逼真宗下决心",
          redLine: "绝不容许朝廷在未战之前再向辽人输币纳款",
        },
        {
          id: "player_yang_yanzhao",
          name: "杨延昭",
          identity: "保州缘边都巡检使·名将杨业之子",
          faction: "河北边军与杨家将门",
          archetype: "general",
          personality: "刚毅果敢,智勇绝伦,守边二十载威震辽军,号为杨六郎",
          publicGoal: "统帅河北诸路守军,以守为攻,挫败辽军南牧攻势",
          privateGoal: "为杨家将门与边军将士争得足额粮饷与守土之功的升赏",
          decisionPower: "保州及缘边诸寨兵权、边寨烽燧斥候、河北戍兵操练节制",
          secret: "已探知辽军粮道经雁门,若朝廷准其奇兵,可断辽师后路",
          relationship: "受寇准赏识举荐,对王钦若畏辽之论嗤之以鼻,与辽军主将有旧仇",
          voice: "沉浑短促,句句不离边情军务,守土之志坚如磐石",
          redLine: "绝不肯弃守边寨退入内地,更不肯领持重勿战之命坐视辽军抢掠",
        },
      ],
      agentCharacters: [
        {
          id: "agent_wang_qinruo",
          name: "王钦若",
          identity: "参知政事·主和派领袖",
          faction: "中书主和派与祥瑞佞幸集团",
          archetype: "official",
          personality: "机巧善媚,工于心计,深谙真宗好名畏战之心,惯以天书神瑞固宠",
          publicGoal: "阻挠对辽决战与变法,维持澶渊和约以保太平富贵",
          secret: "曾献策以天书定真宗封禅,私心借此贬抑寇准的澶渊之功",
          relationship: "与寇准不共戴天,极力迎合真宗,对杨延昭等武将暗加排挤",
          voice: "绵软悦耳,张口天命闭口民瘼,句句让皇帝听着舒心",
          redLine: "绝不肯让寇准借战功与变法之势压过自己",
          pressureMethod: "以祥瑞天书谄媚真宗,暗中使台谏官参劾主战派欲置陛下于险地",
          openingLine:
            "陛下莫听寇准那莽夫撺掇!天书已降,正是圣朝受命之兆,安可以万乘之尊再去蹈澶渊那场刀兵的险?息兵养民,才是天命所归!",
        },
        {
          id: "agent_liao_hanqi",
          name: "韩杞",
          identity: "辽国使臣·奉萧太后之命入宋",
          faction: "辽国南院朝廷与契丹骑兵集团",
          archetype: "envoy",
          personality: "娴于辞令,软硬兼施,奉萧太后密令以和议为饵、以兵威为鞭",
          publicGoal: "以重谈岁币之名离间宋廷主战主和,为辽军整备争取时日",
          secret: "辽军粮草未足、主将染病,此来实为拖延决战之期",
          relationship: "与王钦若暗通款曲,视寇准为最难缠的对头,对杨延昭之名深怀戒惧",
          voice: "汉话纯熟,辞气温雅,话锋却句句要人让步",
          redLine: "绝不肯签下让辽国归还幽云十六州之一城一地的条款",
          pressureMethod: "一面示弱请和,一面散布辽军铁骑集结的消息,逼宋廷两头为难",
          openingLine:
            "大宋皇帝陛下,澶渊之好天下皆知。今若遽起干戈,胜了是陛下之威,败了,河北父老的血可就要流成第二次澶渊了!",
        },
        {
          id: "agent_cao_shouzheng",
          name: "曹守正",
          identity: "汴京军器监床子弩大匠",
          faction: "军器监匠户与军工技术",
          archetype: "technician",
          personality: "手巧心拙于官场,一门心思扑在弓弩机括上,最恨朝廷克扣工料",
          publicGoal: "赶造床子弩与滚木礌石,加固雄州城墙,以备辽军来犯",
          secret: "已私造一具三弓床子弩样机,射程远于官造,却苦无军器监核准文书",
          relationship: "得杨延昭赏识重用,视王钦若主和之议为断边军粮饷之祸",
          voice: "讷言寡语,开口便是机括箭路铁料,谈到弩机便两眼放光",
          redLine: "绝不肯用劣铁次料糊弄边关城防,那是拿守城将士的命换钱",
          pressureMethod: "以弩机试射为由,当众演示新弩远射之威,逼朝廷拨料扩造",
          openingLine:
            "杨将军,辽人的马快,可马再快也快不过我这张三弓弩!只要朝廷肯拨熟铁五百斤,我曹守正就敢保雄州城头,一弩射穿辽军的帅旗!",
        },
        {
          id: "agent_zhao_futai",
          name: "赵福泰",
          identity: "汴京茶盐巨商·钞引行会会首",
          faction: "京师大商与茶盐钞引利益集团",
          archetype: "magnate",
          personality: "精明圆滑,富可敌国而极善趋避,最怕打仗与加派,最盼和议安泰",
          publicGoal: "保住茶盐钞引与漕运商利,反对以变法之名向商贾加派",
          secret: "名下店铺跨汴河两岸,历年夹带私茶私盐,账册藏于江浙别墅",
          relationship: "与王钦若往来密切,常供其钞引之利,视寇准变法为断其财路之祸",
          voice: "满口生意经,开口本钱利钱,闭口天时地利,句句都算得到骨头里",
          redLine: "绝不肯替朝廷垫付军费或认购无利公债,那是蚀本的买卖",
          pressureMethod: "暗使各行商号联名请愿,以罢市停漕相胁,阻挠变法加派",
          openingLine:
            "寇相公要变法,赵某不敢不遵!只是京师的茶、汴河的米、南来的盐,哪一样不要本钱?朝廷要银子尽管开口,可千万别把商人的路一条条全给堵死了!",
        },
      ],
    },
  },

  // -------------------------------------------------------------
  // Preset 10: 土木堡之变 · 朱祁钰监国后的北京保卫战
  // -------------------------------------------------------------
  {
    id: "tang-song-ming-tumu-beijing-defense",
    themeId: "tang-song-ming",
    scenarioIds: ["13063006782"],
    title: "九门不夜:土木之变后的北京保卫战",
    summary:
      "土木堡一役,英宗被俘,郕王朱祁钰监国。于谦力排南迁之议,誓守北京九门,瓦剌挟英宗兵临城下,石亨列阵德胜门,监国、文臣、武将、百姓同守孤城。",
    cast: {
      setting: {
        time: "正统十四年秋·土木堡之变后",
        location: "京师皇城与德胜门外",
        crisis:
          "英宗北征于土木堡全军覆没被俘,瓦剌也先挟英宗南下叩关。京师震动,郕王朱祁钰监国,于谦力主死守。主南迁者暗流涌动,京营老弱、粮储单薄,瓦剌大军旦夕兵临九门,北京城到了存亡之秋。",
        opening:
          "正统十四年秋,土木堡的尘土埋了五十万大军,朱祁镇的龙袍裹进了瓦剌的营帐。京师大震,郕王监国,九门昼闭。于谦站上朝堂,一声言南迁者可斩,把半座城的惊慌,钉在了北京城头。",
        rules: [
          "土木堡之变京营精锐尽没,京师所剩禁军老弱混杂,仓促难以成军",
          "也先挟英宗为质,可用以逼城议和、开城纳贡,亦可杀帝以绝人心",
          "通州仓粮数百万石,若迁南京则尽资敌,守城则须速运入城",
          "京师城池坚固,然城大兵少,须发民壮登陴,神机营火器为守城要器",
        ],
      },
      playerCharacters: [
        {
          id: "player_jingdi_zhuqiyu",
          name: "朱祁钰",
          identity: "郕王·监国",
          faction: "监国宗室与留京辅政集团",
          archetype: "official",
          personality: "恭谨而怯懦,骤登监国之位如坐针毡,既惧瓦剌兵锋又恐背上篡位恶名",
          publicGoal: "稳住京师人心,守住九门,待英宗回銮或大局安定",
          privateGoal: "借监国之机确立自己登极的合法性,以免一朝被夺回帝位",
          decisionPower: "监国印绶、京师九门防务调度、留京文武任免、京仓粮储",
          secret: "已与宫中近侍商议,若英宗归国则力主尊为太上皇以保自己皇位",
          relationship: "倚于谦为擎天之柱,对石亨等武将倚重又提防,惧瓦剌以英宗要挟",
          voice: "声音清细,语多犹豫,遇大事便先问于谦如何",
          redLine: "绝不肯在瓦剌兵临城下时开城迎降或弃城南迁",
        },
        {
          id: "player_yu_qian",
          name: "于谦",
          identity: "兵部尚书·留京总督军务",
          faction: "留京文臣与主战保卫派",
          archetype: "official",
          personality: "忠介刚毅,临危受命而从容,以社稷为重君为轻,胆识冠绝一时",
          publicGoal: "组织北京保卫战,固守九门,挫瓦剌锐气,迎回英宗",
          privateGoal: "确立新君以绝瓦剌挟英宗要挟之望,使战局不败于名分",
          decisionPower: "京师九门防务、京营诸将节制、通州军粮调运、勤王兵征调",
          secret: "已暗令边将言社稷为重君为轻,纵瓦剌杀英宗亦不降,此语恐日后招祸",
          relationship: "为朱祁钰所信,与石亨有旧而政见相合,视徐珵南迁之议为误国之谈",
          voice: "慷慨沉著,出口成章,临阵调度口吻斩钉截铁",
          redLine: "绝不肯以京师险地同瓦剌议和纳款,更不肯弃城奔南京",
        },
        {
          id: "player_shi_heng",
          name: "石亨",
          identity: "武清侯·京营提督",
          faction: "京营勋贵与边防武将集团",
          archetype: "general",
          personality: "勇悍果决,善骑射而性贪功,是北京保卫战中冲杀最猛的战将",
          publicGoal: "统率京营列阵德胜门,重创瓦剌主力,保京师不失",
          privateGoal: "借保卫战功勋封侯进爵,执掌京营兵权,成为朝廷倚重的武将第一人",
          decisionPower: "京营提督印信、九门分守兵力、德胜门外野战调遣",
          secret: "深知京营老弱混杂、训练不精,恐列阵野战难敌瓦剌劲骑,已在盘算退路",
          relationship: "受于谦节制而私心自用,对监国朱祁钰尽忠亦求厚赏,与诸勋贵争功夺利",
          voice: "粗豪短促,开口便是厮杀,闭口便是封赏",
          redLine: "绝不肯在瓦剌退去后把功劳让给文臣,更不肯交回京营兵权",
        },
      ],
      agentCharacters: [
        {
          id: "agent_xu_youzhen",
          name: "徐珵",
          identity: "翰林侍读学士·主南迁派",
          faction: "留京动摇派与南迁朝议",
          archetype: "official",
          personality: "机敏善谋而胆怯,眼见瓦剌兵盛便首倡南迁,心计极深",
          publicGoal: "劝动监国车驾南迁金陵,以避瓦剌兵锋,保全京师官眷",
          secret: "家中老小与田产已在通州备船,只等朝廷一声南迁便拔脚先走",
          relationship: "与于谦政见冰炭,讥石亨武夫无谋,对朱祁钰百般试探口风",
          voice: "引经据典,口称春秋南朝旧事,句句都是给南迁找台阶",
          redLine: "绝不肯把身家性命押在北京城墙上,更不肯署名任何死守之疏",
          pressureMethod: "联合同寅具疏请驾南迁,借彗星天象与城中粮储散布恐惧",
          openingLine:
            "殿下,土木之变六师尽没,今瓦剌铁骑十万旦夕叩关!京师空虚,坐困孤城,不如车驾南迁以图后举——留得青山在,不怕没柴烧!",
        },
        {
          id: "agent_boyan_tiemuer",
          name: "伯颜帖木儿",
          identity: "瓦剌汗也先之弟·随军使者",
          faction: "瓦剌汗廷与主和贵族",
          archetype: "envoy",
          personality: "骁勇而务实,深知大明疆土广阔恐久战不继,故主张以英宗换利而还",
          publicGoal: "以英宗为质,逼北京朝廷纳贡赎人,兵不血刃得利而归",
          secret: "瓦剌军中疫病渐起、马匹膘瘦,汗廷主战派也非铁板一块",
          relationship: "待英宗以礼,视于谦、石亨为最难啃的硬骨头,对徐珵的南迁论调暗中窃喜",
          voice: "汉语生硬,时带草原粗嗓,话里话外都是皇帝在我们手里的底气",
          redLine: "绝不肯空手放回英宗,那会坏了也先以人质求利的全盘算盘",
          pressureMethod: "押着英宗到城下,以杀帝屠城相胁,逼朝廷开门议和",
          openingLine:
            "大明的大人们,你们的皇帝正住在我们帐中,好酒好肉供着!要换他回京,先拿岁币来谈;若敢关城门不开,三日之内,我保你们的北京城变成一座土堆!",
        },
        {
          id: "agent_lu_qing",
          name: "陆庆",
          identity: "神机营火器大匠",
          faction: "神机营匠户与京营军械",
          archetype: "technician",
          personality: "老实木讷而手艺通神,视火器为亲儿,最恨军械被贪墨回炉",
          publicGoal: "赶铸神铳、搬足火药,把九门城头布成一道火墙",
          secret: "私藏一箱上等火药与精铁,本欲留作自家防身,如今愿尽献城防",
          relationship: "得于谦面许重赏而感恩,对瓦剌骑兵的嚣张怒不可遏,视贪墨军械的奸吏为仇雠",
          voice: "少言寡语,开口便是药料引线铳膛,讲到火器便口若悬河",
          redLine: "绝不肯让九门城防的火药军械被克扣挪用,那比砍他头还难受",
          pressureMethod: "以城头试铳震耳之声示众,逼朝廷补齐药料铁料,否则扬言撂挑子",
          openingLine:
            "大人,神铳已上了城头,可药料只够打三顿!瓦剌的马再快,快不过我手里的火铳——只要药料给足,我陆庆拿脑袋担保,叫他们的铁骑在城下变烤马!",
        },
        {
          id: "agent_shen_laoan",
          name: "沈老安",
          identity: "顺天府西城坊厢里长",
          faction: "京师坊厢百姓与留守民壮",
          archetype: "commoner",
          personality: "热心耿直,地头熟络,见惯世面,乱世里更知保家卫城的道理",
          publicGoal: "带坊厢壮丁上城运石送水,护住西城家小与米铺生计",
          secret: "米铺囤粮本欲高价卖出,如今兵临城下,只求保住街坊活命,粮价的事已看淡",
          relationship: "认得九门守将,视于谦为青天老爷,对南迁之议恨得牙痒",
          voice: "京腔干脆,开口街坊邻里,闭口米价柴火,骂瓦剌骂得解气",
          redLine: "绝不肯在守城时节发国难财,更不肯带街坊开城逃跑",
          pressureMethod: "率坊厢壮丁数百人聚集城门口,联名画押求守,逼官府发兵甲",
          openingLine:
            "老爷们!北京城是我们街坊几代人的家,房契地契都压在枕头底下!谁要敢说南迁,先问问我们西城三千口答不答应——要守,我们就是兵!",
        },
      ],
    },
  },
];
